import {beforeEach,describe,expect,it} from 'vitest';
import {syntheticDisputes,SyntheticDisputeError,type DisputeActor} from '../../server/lib/syntheticDisputes.js';
import {financialSandbox} from '../../server/lib/financialSandboxStore.js';
const admin:DisputeActor={id:'admin_maker',email:'maker@example.test',correlationId:'corr-maker',actorType:'admin'};
const checker:DisputeActor={id:'external_checker_0123456789abcdef',email:'checker@example.test',correlationId:'corr-checker',actorType:'independent_checker'};
const due=()=>new Date(Date.now()+86400000).toISOString();
beforeEach(()=>{delete process.env.DATABASE_URL;delete process.env.NODE_ENV;syntheticDisputes.resetForTests();});
async function open(extra:Record<string,unknown>={}){return syntheticDisputes.create({caseType:'customer_dispute',category:'duplicate payment',priority:'high',customerReference:'syn_customer_001',summary:'Customer reports a duplicate payment',customerClaim:'The same payment appears twice on the account.',dueAt:due(),...extra},admin);}
describe('synthetic dispute controls',()=>{
 it('creates linked hash-backed cases and validates evidence fingerprints',async()=>{const item=await open({transactionId:'syn_tx_reference',transferId:'syn_transfer_reference',monitoringAlertId:'syn_alert_reference',reconciliationExceptionId:'syn_recon_exception_reference'});expect(item.caseSha256).toMatch(/^[a-f0-9]{64}$/);expect(item.synthetic).toBe(true);await expect(syntheticDisputes.addEvidence(item.id,{label:'Customer statement',controlledReference:'controlled://case/statement',evidenceSha256:'bad'},admin)).rejects.toMatchObject({code:'VALIDATION_ERROR'});await syntheticDisputes.addEvidence(item.id,{label:'Customer statement',controlledReference:'controlled://case/statement',evidenceSha256:'a'.repeat(64)},admin);expect((await syntheticDisputes.list()).cases[0].evidence).toHaveLength(1);});
 it('requires investigation and independent maker-checker approval',async()=>{const item=await open();await expect(syntheticDisputes.submitRemediation(item.id,{type:'no_financial_action',reason:'Close after documented investigation.'},admin)).rejects.toMatchObject({code:'INVALID_TRANSITION'});await syntheticDisputes.investigate(item.id,{owner:'Dispute Operations',notes:'Reviewed the customer claim and linked records.'},admin);await syntheticDisputes.submitRemediation(item.id,{type:'no_financial_action',reason:'Close after documented investigation.'},admin);await expect(syntheticDisputes.review(item.id,'approved','Approved after independent evidence review.',{...admin,actorType:'independent_checker'})).rejects.toBeInstanceOf(SyntheticDisputeError);const resolved=await syntheticDisputes.review(item.id,'approved','Approved after independent evidence review.',checker);expect(resolved.status).toBe('resolved');});
 it('posts financial remediation only as an idempotent balanced reversal',async()=>{const source=await financialSandbox.createAccount({name:'Source',type:'personal',asset:'GBP',idempotencyKey:'acct-source'},admin),destination=await financialSandbox.createAccount({name:'Destination',type:'savings',asset:'GBP',idempotencyKey:'acct-dest'},admin);await financialSandbox.adjust({accountId:source.id,amount:'100.00',direction:'credit',reason:'Synthetic opening balance',reference:'TEST',confirmed:true,idempotencyKey:'fund-source'},admin);const original=await financialSandbox.transfer({sourceAccountId:source.id,destinationAccountId:destination.id,amount:'25.00',reason:'Synthetic disputed transfer',idempotencyKey:'original-transfer'},admin);const item=await open({transactionId:original.id});await syntheticDisputes.investigate(item.id,{owner:'Dispute Operations',notes:'Confirmed the synthetic transaction is eligible.'},admin);const remediationReason='Refund the duplicate synthetic payment in full.';await syntheticDisputes.submitRemediation(item.id,{type:'full_refund',reason:remediationReason},admin);const resolved=await syntheticDisputes.review(item.id,'approved','Approved because evidence confirms the duplicate.',checker);const reversal=await financialSandbox.getTransaction(resolved.remediationTransactionId!);expect(reversal.kind).toBe('reversal');expect(reversal.reversesId).toBe(original.id);expect(reversal.lines.reduce((sum,line)=>sum+line.debitMinor,0n)).toBe(reversal.lines.reduce((sum,line)=>sum+line.creditMinor,0n));const retry=await financialSandbox.reverse(original.id,`Dispute ${item.reference}: ${remediationReason}`,`dispute-remediation:${item.id}`,checker);expect(retry.id).toBe(reversal.id);});
 it('records notifications without falsely claiming delivery and exports evidence',async()=>{const item=await open();const note=await syntheticDisputes.notify(item.id,{channel:'email',subject:'Case received',message:'Your dispute has been recorded for investigation.'},admin);expect(note.deliveryStatus).toBe('recorded');const exported=await syntheticDisputes.export(item.id,admin);expect(exported.record.evidenceSha256).toMatch(/^[a-f0-9]{64}$/);expect(exported.content).toContain('directBalanceEditing');expect(exported.content).not.toContain('password');});
});
