import { beforeEach, describe, expect, it } from 'vitest';
import { syntheticTransactionMonitoring, type MonitoringActor } from '../../server/lib/syntheticTransactionMonitoring';
import type { SandboxTransaction } from '../../server/lib/financialSandbox';

const admin:MonitoringActor={id:'admin-1',email:'admin@example.test',correlationId:'corr-admin',actorType:'admin'};
const checker:MonitoringActor={id:'external_checker_0123456789abcdef',email:'checker@example.test',correlationId:'corr-checker',actorType:'independent_checker'};
const system:MonitoringActor={id:'monitoring_engine',email:'system@local.invalid',correlationId:'corr-scan',actorType:'system'};
function tx(index:number, amountMinor=40_000n):SandboxTransaction{return {id:`syn_tx_monitor_${index}`,reference:`SYN-MONITOR-${index}`,idempotencyKey:`monitor-${index}`,kind:'internal_transfer',status:'completed',asset:'USD',amountMinor,sourceAccountId:'syn_account_subject',destinationAccountId:`syn_account_destination_${index}`,reason:'Synthetic monitoring fixture',executionSource:'SIMULATION',synthetic:true,lines:[],createdAt:new Date(Date.UTC(2026,0,1,0,index)).toISOString(),updatedAt:new Date(Date.UTC(2026,0,1,0,index)).toISOString()};}

describe('synthetic transaction monitoring',()=>{
  beforeEach(()=>{delete process.env.DATABASE_URL;process.env.NODE_ENV='test';syntheticTransactionMonitoring.resetForTests();});
  it('generates deduplicated velocity alerts with linked hashed snapshots',async()=>{const first=await syntheticTransactionMonitoring.scan([tx(1),tx(2),tx(3)],system);expect(first).toHaveLength(2);expect(first.map(x=>x.ruleKey).sort()).toEqual(['velocity_amount','velocity_count']);expect(first[0].links).toHaveLength(3);expect(first[0].links.every(link=>/^[a-f0-9]{64}$/.test(link.snapshotSha256))).toBe(true);const second=await syntheticTransactionMonitoring.scan([tx(1),tx(2),tx(3)],system);expect(second.map(x=>x.id)).toEqual(first.map(x=>x.id));expect(await syntheticTransactionMonitoring.list()).toHaveLength(2);});
  it('requires reasoned review and an independent checker resolution',async()=>{const [alert]=await syntheticTransactionMonitoring.scan([tx(1),tx(2),tx(3,10_000n)],system);await expect(syntheticTransactionMonitoring.transition(alert.id,'reviewing','short',admin)).rejects.toMatchObject({code:'INVALID_RATIONALE'});const reviewed=await syntheticTransactionMonitoring.transition(alert.id,'reviewing','Review the linked synthetic velocity records.',admin);expect(reviewed.status).toBe('reviewing');const submitted=await syntheticTransactionMonitoring.submitResolution(alert.id,'The pattern is consistent with a synthetic load-test fixture.',admin);expect(submitted.status).toBe('resolution_pending');await expect(syntheticTransactionMonitoring.resolve(alert.id,'false_positive','Independent review confirms the load-test explanation.',admin)).rejects.toMatchObject({code:'INDEPENDENT_CHECKER_REQUIRED'});const resolved=await syntheticTransactionMonitoring.resolve(alert.id,'false_positive','Independent review confirms the load-test explanation.',checker);expect(resolved.status).toBe('closed_false_positive');expect(resolved.resolvedBy).toBe(checker.id);expect(resolved.events.map(event=>event.action)).toEqual(['alert_generated','review_started','resolution_submitted','alert_resolved']);});
  it('escalates an alert to a synthetic case before checker confirmation',async()=>{const alerts=await syntheticTransactionMonitoring.scan([tx(4),tx(5),tx(6,5_000n)],system);const escalated=await syntheticTransactionMonitoring.transition(alerts[0].id,'escalated','Multiple linked records require a synthetic case review.',admin);expect(escalated.caseId).toMatch(/^syn_case_/);await syntheticTransactionMonitoring.submitResolution(escalated.id,'Retain the alert as a synthetic monitoring case.',admin);const resolved=await syntheticTransactionMonitoring.resolve(escalated.id,'case','Independent checker confirms the synthetic case classification.',checker);expect(resolved.status).toBe('closed_case');expect(resolved.caseId).toBe(escalated.caseId);});
  it('rejects non-synthetic transaction input',async()=>{await expect(syntheticTransactionMonitoring.scan([{...tx(1),synthetic:false} as unknown as SandboxTransaction],system)).rejects.toMatchObject({code:'SYNTHETIC_TRANSACTION_REQUIRED'});});
});

