import {beforeEach,describe,expect,it} from 'vitest';
import type {SandboxTransaction} from '../../server/lib/financialSandbox.js';
import type {MoneyMovementInstruction} from '../../server/lib/moneyMovementSimulation.js';
import {syntheticReconciliation} from '../../server/lib/syntheticReconciliation.js';

const admin={id:'admin-maker',email:'admin@example.test',correlationId:'corr-maker',actorType:'admin' as const};
const checker={id:'external_checker_1234567890abcdef',email:'checker@example.test',correlationId:'corr-checker',actorType:'independent_checker' as const};
function transaction(overrides:Partial<SandboxTransaction>={}):SandboxTransaction{return {id:'syn_tx_11111111-1111-1111-1111-111111111111',reference:'SYN-ABC123',idempotencyKey:'key-1',kind:'internal_transfer',status:'completed',asset:'GBP',amountMinor:10_000n,sourceAccountId:'syn_source_account',destinationAccountId:'syn_destination_account',reason:'synthetic test',executionSource:'SIMULATION',synthetic:true,lines:[{accountId:'syn_source_account',asset:'GBP',debitMinor:10_000n,creditMinor:0n},{accountId:'syn_destination_account',asset:'GBP',debitMinor:0n,creditMinor:10_000n}],createdAt:'2026-08-13T08:00:00.000Z',updatedAt:'2026-08-13T08:00:00.000Z',...overrides};}
function instruction(overrides:Partial<MoneyMovementInstruction>={}):MoneyMovementInstruction{return {id:'syn_rail_22222222-2222-2222-2222-222222222222',reference:'SYN-RAIL-ABC123',rail:'ach',direction:'internal',status:'settled',asset:'GBP',amountMinor:10_000n,sourceReference:'syn_source_account',destinationReference:'syn_destination_account',memo:'synthetic match',providerAdapterState:'DISCONNECTED',executionSource:'SIMULATION',synthetic:true,createdAt:'2026-08-13T08:00:00.000Z',updatedAt:'2026-08-13T08:00:00.000Z',...overrides};}

describe('synthetic reconciliation',()=>{
  beforeEach(()=>syntheticReconciliation.resetForTests());
  it('matches provider, transaction and balanced journal snapshots',async()=>{const run=await syntheticReconciliation.run([transaction()],[instruction()],'2026-08-13',admin);expect(run.status).toBe('completed');expect(run.matchedCount).toBe(1);expect(run.exceptionCount).toBe(0);expect(run.snapshotSha256).toMatch(/^[a-f0-9]{64}$/);});
  it('detects missing, mismatched and unbalanced records',()=>{expect(syntheticReconciliation.detect([transaction({lines:[]})],[])[0].outcome).toBe('missing_journal');expect(syntheticReconciliation.detect([transaction({lines:[{accountId:'a',asset:'GBP',debitMinor:10_000n,creditMinor:0n},{accountId:'b',asset:'GBP',debitMinor:0n,creditMinor:9_000n}]})],[instruction()])[0].outcome).toBe('unbalanced_journal');expect(syntheticReconciliation.detect([],[instruction()])[0].outcome).toBe('missing_transaction');});
  it('requires investigation and an independent checker before closure',async()=>{await syntheticReconciliation.run([transaction()],[],'2026-08-13',admin);const exception=(await syntheticReconciliation.list()).exceptions[0];await syntheticReconciliation.investigate(exception.id,{owner:'Finance control',notes:'Provider instruction is missing from the synthetic control feed.'},admin);await syntheticReconciliation.submitResolution(exception.id,'Document the missing instruction and rerun the next daily control.',admin);await expect(syntheticReconciliation.resolve(exception.id,'resolved','Maker must not approve their own proposed resolution.',{...admin,actorType:'admin'})).rejects.toMatchObject({code:'INDEPENDENT_CHECKER_REQUIRED'});const closed=await syntheticReconciliation.resolve(exception.id,'resolved','Independent evidence confirms the exception remediation is complete.',checker);expect(closed.status).toBe('resolved');expect(closed.events.at(-1)?.actorType).toBe('independent_checker');});
  it('exports hash-backed evidence without exposing an activation control',async()=>{const run=await syntheticReconciliation.run([transaction()],[instruction()],'2026-08-13',admin);const result=await syntheticReconciliation.export(run.id,admin);expect(result.record.evidenceSha256).toMatch(/^[a-f0-9]{64}$/);expect(result.content).toContain('"balanceMutation": false');expect(result.content).toContain('"liveTransactionUnlock": false');expect(result.content).not.toContain('DATABASE_URL');});
});
