import { Helmet } from '@dr.pogodin/react-helmet';
import { ArrowLeft, BellRing, CalendarClock, CheckCircle2, Loader2, Pencil, Plus, ReceiptText, Trash2, X } from 'lucide-react';
import { useEffect, useMemo, useState, type ReactElement } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useCustomerAuth } from '@/lib/customerAuth';

type BillStatus = 'scheduled' | 'paused' | 'completed';
interface Bill { id: string; payee: string; category: string; currency: string; amount_minor: string; frequency: string; next_due_date: string; reminder_days: number; status: BillStatus; }
interface Form { id?: string; payee: string; category: string; currency: string; amount: string; frequency: string; nextDueDate: string; reminderDays: string; status: BillStatus; }
const today = () => new Date().toISOString().slice(0, 10);
const EMPTY: Form = { payee: '', category: 'Household', currency: 'GBP', amount: '', frequency: 'monthly', nextDueDate: today(), reminderDays: '3', status: 'scheduled' };
const currencies = ['GBP', 'EUR', 'USD', 'CAD', 'AUD', 'CHF'];
const frequencies = ['one_time', 'weekly', 'monthly', 'quarterly', 'annually'];
const minor = (value: string) => String(Math.round(Number(value) * 100));
const major = (value: string) => (Number(value) / 100).toFixed(2);
const money = (value: string, currency: string) => new Intl.NumberFormat('en-GB', { style: 'currency', currency }).format(Number(value) / 100);

export default function BillsPage() {
  const { customer, loading } = useCustomerAuth(); const navigate = useNavigate();
  const [bills, setBills] = useState<Bill[]>([]); const [fetching, setFetching] = useState(true); const [saving, setSaving] = useState(false); const [form, setForm] = useState<Form | null>(null); const [message, setMessage] = useState('');
  useEffect(() => { if (!loading && !customer) navigate('/login?reason=session_expired', { replace: true }); }, [customer, loading, navigate]);
  async function load() { setFetching(true); try { const response = await fetch('/api/users/bills', { credentials: 'same-origin' }); if (response.ok) setBills((await response.json()).bills ?? []); } finally { setFetching(false); } }
  useEffect(() => { if (customer) void load(); }, [customer]);
  const scheduled = useMemo(() => bills.filter(bill => bill.status === 'scheduled'), [bills]);
  function edit(bill: Bill) { setForm({ id: bill.id, payee: bill.payee, category: bill.category, currency: bill.currency, amount: major(bill.amount_minor), frequency: bill.frequency, nextDueDate: bill.next_due_date.slice(0, 10), reminderDays: String(bill.reminder_days), status: bill.status }); }
  async function save(action: 'create' | 'update' | 'delete', value: Form) { setSaving(true); setMessage(''); try { const response = await fetch('/api/users/bills', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(action === 'delete' ? { action, id: value.id } : { action, id: value.id, payee: value.payee, category: value.category, currency: value.currency, amountMinor: minor(value.amount), frequency: value.frequency, nextDueDate: value.nextDueDate, reminderDays: Number(value.reminderDays), status: value.status }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? 'Unable to save bill schedule.'); setForm(null); setMessage(action === 'delete' ? 'Bill schedule removed.' : 'Bill schedule saved.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to save bill schedule.'); } finally { setSaving(false); } }
  if (loading || !customer) return <div className="grid min-h-screen place-items-center bg-background"><Loader2 className="animate-spin text-primary" /></div>;
  return <main className="min-h-screen bg-background text-foreground"><Helmet><title>Bills & Payments — City Gate Capital</title><meta name="robots" content="noindex, nofollow" /></Helmet>
    <header className="sticky top-0 z-40 border-b border-white/5 bg-[rgba(10,10,10,.92)] backdrop-blur-xl"><div className="mx-auto flex h-14 max-w-3xl items-center gap-3 px-4"><Link to="/dashboard" className="grid h-8 w-8 place-items-center rounded-xl border border-white/8 bg-white/5"><ArrowLeft size={15} /></Link><ReceiptText size={16} className="text-primary" /><span className="text-sm font-semibold">Bills & Payments</span><button onClick={() => setForm({ ...EMPTY })} className="ml-auto flex items-center gap-2 rounded-xl border border-primary/25 bg-primary/10 px-3 py-2 text-xs font-semibold text-primary"><Plus size={13} /> Schedule</button></div></header>
    <div className="mx-auto max-w-3xl space-y-6 px-4 py-6"><section className="rounded-3xl border border-primary/20 bg-[radial-gradient(circle_at_90%_0%,rgba(201,168,76,.14),transparent_45%),rgba(255,255,255,.02)] p-6"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-primary">Payment planning</p><div className="mt-3 flex items-end justify-between"><div><h1 className="text-2xl font-bold">Stay ahead of every bill</h1><p className="mt-2 text-xs leading-6 text-foreground/45">Organise due dates and reminders in one secure place.</p></div><div className="text-right"><p className="text-3xl font-bold text-primary">{scheduled.length}</p><p className="text-[10px] text-foreground/30">scheduled</p></div></div></section>
      <div className="flex items-start gap-3 rounded-2xl border border-amber-400/15 bg-amber-400/5 p-4"><BellRing size={15} className="mt-0.5 text-primary" /><p className="text-[10px] leading-5 text-foreground/40">This workspace tracks schedules and reminders only. Payment execution remains unavailable until an authorised provider is connected.</p></div>
      {message && <div className="rounded-2xl border border-primary/15 bg-primary/5 px-4 py-3 text-xs text-primary">{message}</div>}
      {form && <Editor form={form} setForm={setForm} saving={saving} onSave={() => void save(form.id ? 'update' : 'create', form)} onDelete={form.id ? () => void save('delete', form) : undefined} />}
      {fetching ? <div className="grid place-items-center py-16"><Loader2 className="animate-spin text-foreground/25" /></div> : bills.length === 0 ? <button onClick={() => setForm({ ...EMPTY })} className="w-full rounded-3xl border border-dashed border-white/10 py-16"><CalendarClock className="mx-auto text-primary/50" /><p className="mt-4 text-sm font-semibold text-foreground/60">No bills scheduled</p><p className="mt-1 text-xs text-foreground/30">Add a bill to create a reminder.</p></button> : <div className="space-y-3">{bills.map(bill => <article key={bill.id} className="flex items-center gap-4 rounded-2xl border border-white/7 bg-white/[.02] p-4"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-primary/10 text-primary"><ReceiptText size={17} /></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="truncate text-sm font-bold">{bill.payee}</h2><span className="rounded-full bg-white/5 px-2 py-0.5 text-[9px] uppercase text-foreground/35">{bill.status}</span></div><p className="mt-1 text-[10px] text-foreground/30">{bill.category} · {bill.frequency.replace('_', ' ')} · due {new Date(`${bill.next_due_date.slice(0,10)}T12:00:00`).toLocaleDateString('en-GB')}</p></div><div className="text-right"><p className="text-sm font-bold text-primary">{money(bill.amount_minor, bill.currency)}</p><button onClick={() => edit(bill)} className="mt-2 inline-flex items-center gap-1 text-[10px] text-foreground/35"><Pencil size={10} /> Edit</button></div></article>)}</div>}
    </div></main>;
}

function Editor({ form, setForm, saving, onSave, onDelete }: { form: Form; setForm: (value: Form | null) => void; saving: boolean; onSave: () => void; onDelete?: () => void }) { const patch = (key: keyof Form, value: string) => setForm({ ...form, [key]: value }); return <section className="rounded-3xl border border-primary/20 bg-[#0b0b0a] p-5"><div className="flex justify-between"><h2 className="text-sm font-bold">{form.id ? 'Edit bill schedule' : 'Add a bill schedule'}</h2><button onClick={() => setForm(null)}><X size={17} /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Payee"><input value={form.payee} onChange={e => patch('payee', e.target.value)} maxLength={100} /></Field><Field label="Category"><input value={form.category} onChange={e => patch('category', e.target.value)} maxLength={50} /></Field><Field label="Amount"><input type="number" min="0.01" step="0.01" value={form.amount} onChange={e => patch('amount', e.target.value)} /></Field><Field label="Currency"><select value={form.currency} onChange={e => patch('currency', e.target.value)}>{currencies.map(v => <option key={v}>{v}</option>)}</select></Field><Field label="Frequency"><select value={form.frequency} onChange={e => patch('frequency', e.target.value)}>{frequencies.map(v => <option key={v} value={v}>{v.replace('_', ' ')}</option>)}</select></Field><Field label="Next due date"><input type="date" value={form.nextDueDate} onChange={e => patch('nextDueDate', e.target.value)} /></Field><Field label="Reminder days"><input type="number" min="0" max="30" value={form.reminderDays} onChange={e => patch('reminderDays', e.target.value)} /></Field><Field label="Status"><select value={form.status} onChange={e => patch('status', e.target.value)}><option value="scheduled">Scheduled</option><option value="paused">Paused</option><option value="completed">Completed</option></select></Field></div><div className="mt-5 flex gap-2">{onDelete && <button onClick={onDelete} disabled={saving} className="grid h-11 w-11 place-items-center rounded-xl border border-red-500/20 text-red-400"><Trash2 size={14} /></button>}<button onClick={onSave} disabled={saving || form.payee.trim().length < 2 || !form.amount} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-primary font-bold text-black disabled:opacity-40">{saving ? <Loader2 size={14} className="animate-spin" /> : <CheckCircle2 size={14} />} Save schedule</button></div></section>; }
function Field({ label, children }: { label: string; children: ReactElement }) { return <label className="space-y-1.5 text-[10px] font-semibold uppercase tracking-wider text-foreground/35">{label}<span className="block [&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:border-white/8 [&>*]:bg-white/[.04] [&>*]:px-3 [&>*]:py-2.5 [&>*]:text-xs [&>*]:font-normal [&>*]:normal-case [&>*]:tracking-normal [&>*]:text-foreground/75 [&>*]:outline-none">{children}</span></label>; }
