import { Helmet } from '@dr.pogodin/react-helmet';
import { ArrowLeft, Clock3, Gift, Loader2, LockKeyhole, Sparkles, WalletCards } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useCustomerAuth } from '@/lib/customerAuth';

interface RewardAccount { pointsBalance: string; cashbackMinor: string; cashbackCurrency: string; membershipTier: string; updatedAt: string | null; }
interface RewardEvent { id: string; eventType: string; points: string; cashbackMinor: string; currency: string; description: string; occurredAt: string; }
interface RewardData { enabled: boolean; account: RewardAccount | null; activity: RewardEvent[]; offers: unknown[]; }
const money = (minor: string, currency: string) => new Intl.NumberFormat('en-GB', { style: 'currency', currency }).format(Number(minor) / 100);

export default function RewardsPage() {
  const { customer, loading } = useCustomerAuth(); const navigate = useNavigate();
  const [data, setData] = useState<RewardData | null>(null); const [fetching, setFetching] = useState(true);
  useEffect(() => { if (!loading && !customer) navigate('/login?reason=session_expired', { replace: true }); }, [customer, loading, navigate]);
  useEffect(() => { if (!customer) return; fetch('/api/users/rewards', { credentials: 'same-origin' }).then(response => response.ok ? response.json() : null).then(setData).finally(() => setFetching(false)); }, [customer]);
  if (loading || !customer || fetching) return <div className="grid min-h-screen place-items-center bg-background"><Loader2 className="animate-spin text-primary" /></div>;
  return <main className="min-h-screen bg-background text-foreground"><Helmet><title>Rewards & Benefits — City Gate Capital</title><meta name="robots" content="noindex, nofollow" /></Helmet>
    <header className="sticky top-0 z-40 border-b border-white/5 bg-[rgba(10,10,10,.92)] backdrop-blur-xl"><div className="mx-auto flex h-14 max-w-3xl items-center gap-3 px-4"><Link to="/dashboard" className="grid h-8 w-8 place-items-center rounded-xl border border-white/8 bg-white/5"><ArrowLeft size={15} /></Link><Gift size={16} className="text-primary" /><span className="text-sm font-semibold">Rewards & Benefits</span></div></header>
    <div className="mx-auto max-w-3xl space-y-6 px-4 py-6">{!data?.enabled ? <section className="rounded-3xl border border-white/7 bg-white/[.02] px-6 py-16 text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-3xl border border-primary/20 bg-primary/10 text-primary"><LockKeyhole size={25} /></span><h1 className="mt-5 text-2xl font-bold">Rewards are not currently available</h1><p className="mx-auto mt-3 max-w-md text-xs leading-6 text-foreground/40">City Gate Capital will display eligible rewards and membership benefits here when the programme is enabled for customers.</p></section> : <>
      <section className="rounded-3xl border border-primary/20 bg-[radial-gradient(circle_at_90%_0%,rgba(201,168,76,.18),transparent_45%),rgba(255,255,255,.02)] p-6"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-primary">{data.account?.membershipTier ?? 'Member'} benefits</p><h1 className="mt-3 text-3xl font-bold">{Number(data.account?.pointsBalance ?? 0).toLocaleString()} points</h1><p className="mt-2 text-xs text-foreground/40">Verified rewards balance</p></div><Sparkles className="text-primary" size={28} /></div><div className="mt-6 grid grid-cols-2 gap-3"><Summary icon={WalletCards} label="Cashback" value={money(data.account?.cashbackMinor ?? '0', data.account?.cashbackCurrency ?? 'GBP')} /><Summary icon={Gift} label="Eligible offers" value={String(data.offers.length)} /></div></section>
      <section><h2 className="text-sm font-bold">Rewards activity</h2>{data.activity.length === 0 ? <div className="mt-3 rounded-3xl border border-dashed border-white/10 py-12 text-center"><Clock3 className="mx-auto text-foreground/20" /><p className="mt-3 text-sm font-semibold text-foreground/45">No rewards activity yet</p><p className="mt-1 text-xs text-foreground/25">Eligible provider-confirmed activity will appear here.</p></div> : <div className="mt-3 space-y-2">{data.activity.map(event => <article key={event.id} className="flex items-center gap-3 rounded-2xl border border-white/7 bg-white/[.02] p-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-primary/10 text-primary"><Gift size={14} /></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{event.description}</p><p className="mt-1 text-[10px] uppercase text-foreground/30">{event.eventType} · {new Date(event.occurredAt).toLocaleDateString('en-GB')}</p></div><p className="text-xs font-bold text-primary">{Number(event.points) !== 0 ? `${Number(event.points).toLocaleString()} pts` : money(event.cashbackMinor, event.currency)}</p></article>)}</div>}</section>
    </>}<div className="rounded-2xl border border-white/5 bg-white/[.015] p-4 text-[10px] leading-5 text-foreground/30">Rewards records are provider or administrator authored. Customers cannot create points, cashback, offers, or redemptions.</div></div>
  </main>;
}
function Summary({ icon: Icon, label, value }: { icon: typeof Gift; label: string; value: string }) { return <div className="rounded-2xl border border-white/7 bg-black/20 p-4"><Icon size={14} className="text-primary" /><p className="mt-3 text-[10px] text-foreground/30">{label}</p><p className="mt-1 text-lg font-bold">{value}</p></div>; }
