import { Helmet } from '@dr.pogodin/react-helmet';
import { ArrowLeft, BookOpen, FileText, HelpCircle, Loader2, Search, Users } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { useCustomerAuth } from '@/lib/customerAuth';

interface Result { type: 'transaction'|'statement'|'beneficiary'|'support'|'help'; id: string; title: string; description: string; href: string; }
const icons = { transaction: FileText, statement: FileText, beneficiary: Users, support: HelpCircle, help: BookOpen };

export default function CustomerSearchPage() {
  const { customer, loading } = useCustomerAuth(); const navigate=useNavigate(); const [params,setParams]=useSearchParams();
  const [query,setQuery]=useState(params.get('q') ?? ''); const [results,setResults]=useState<Result[]>([]); const [searching,setSearching]=useState(false); const [searched,setSearched]=useState(false);
  useEffect(()=>{if(!loading&&!customer)navigate('/login?reason=session_expired',{replace:true});},[customer,loading,navigate]);
  useEffect(()=>{if(!customer)return; const q=query.trim(); if(q.length<2){setResults([]);setSearched(false);return;} const controller=new AbortController(); const timer=setTimeout(async()=>{setSearching(true);try{const response=await fetch(`/api/users/search?q=${encodeURIComponent(q)}`,{credentials:'same-origin',signal:controller.signal});if(response.ok){setResults((await response.json()).results??[]);setSearched(true);setParams({q},{replace:true});}}catch(error){if(!(error instanceof DOMException&&error.name==='AbortError'))setResults([]);}finally{if(!controller.signal.aborted)setSearching(false);}},250);return()=>{clearTimeout(timer);controller.abort();};},[query,customer,setParams]);
  if(loading||!customer)return <div className="grid min-h-screen place-items-center bg-background"><Loader2 className="animate-spin text-primary"/></div>;
  return <main className="min-h-screen bg-background text-foreground"><Helmet><title>Search — City Gate Capital</title><meta name="robots" content="noindex, nofollow"/></Helmet><header className="sticky top-0 z-40 border-b border-white/5 bg-[rgba(10,10,10,.94)] backdrop-blur-xl"><div className="mx-auto flex h-14 max-w-3xl items-center gap-3 px-4"><Link to="/dashboard" className="grid h-8 w-8 place-items-center rounded-xl border border-white/8 bg-white/5"><ArrowLeft size={15}/></Link><Search size={16} className="text-primary"/><span className="text-sm font-semibold">Search</span></div></header><div className="mx-auto max-w-3xl px-4 py-6"><div className="relative"><Search size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-foreground/25"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search transactions, statements, beneficiaries and help…" className="w-full rounded-2xl border border-primary/20 bg-white/[.035] py-4 pl-12 pr-12 text-sm outline-none focus:border-primary/50"/>{searching&&<Loader2 size={16} className="absolute right-4 top-1/2 -translate-y-1/2 animate-spin text-primary"/>}</div><p className="mt-3 text-[10px] text-foreground/25">Search results are limited to your own customer records.</p><div className="mt-6 space-y-2">{results.map(result=>{const Icon=icons[result.type]??Search;return <Link key={`${result.type}:${result.id}`} to={result.href} className="flex items-center gap-3 rounded-2xl border border-white/7 bg-white/[.02] p-4 transition-colors hover:border-primary/20"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><Icon size={15}/></span><div className="min-w-0"><p className="truncate text-sm font-semibold">{result.title}</p><p className="mt-1 truncate text-[10px] text-foreground/35">{result.description}</p></div></Link>;})}{searched&&!searching&&results.length===0&&<div className="rounded-3xl border border-dashed border-white/10 py-16 text-center"><Search className="mx-auto text-foreground/15"/><p className="mt-3 text-sm font-semibold text-foreground/45">No matching results</p><p className="mt-1 text-xs text-foreground/25">Try a reference, recipient, description, or help topic.</p></div>}</div></div></main>;
}
