import { Helmet } from '@dr.pogodin/react-helmet';
import { ArrowLeft, CheckCircle2, Loader2, ShieldCheck } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

type Bundle = { case: { id: string; caseType: string; status: string }; evidence: Array<{ id: string; kind: string; reference: string }> };
export default function OnboardingPage() {
  const [bundle, setBundle] = useState<Bundle | null>(null);
  const [kind, setKind] = useState('identity'); const [reference, setReference] = useState('');
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  async function load() { const r = await fetch('/api/users/onboarding'); if (r.ok) setBundle(await r.json()); }
  useEffect(() => { void load(); }, []);
  async function addEvidence() { setBusy(true); setMessage(''); const r=await fetch('/api/users/onboarding/evidence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,referenceType:'provider',reference})}); const b=await r.json(); setMessage(r.ok?'Evidence reference added.':b.error); if(r.ok){setReference('');await load();} setBusy(false); }
  async function submit() { setBusy(true); const r=await fetch('/api/users/onboarding/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}); const b=await r.json(); setMessage(r.ok?'Case submitted for compliance review.':b.error); await load(); setBusy(false); }
  return <main className="min-h-screen bg-background text-foreground p-6"><Helmet><title>Customer Onboarding | City Gate Capital</title></Helmet><div className="max-w-2xl mx-auto space-y-6"><Link to="/dashboard" className="inline-flex gap-2 text-sm text-foreground/50"><ArrowLeft size={16}/>Dashboard</Link><div><h1 className="text-3xl font-bold">Customer onboarding</h1><p className="text-sm text-foreground/50 mt-2">Submit an opaque reference issued by an approved identity provider. Do not paste identity data, passwords, document contents or public file links.</p></div>{!bundle?<Loader2 className="animate-spin"/>:<><div className="rounded-2xl border border-white/10 p-5"><div className="flex justify-between"><span className="font-semibold">{bundle.case.caseType} case</span><span className="text-primary uppercase text-xs">{bundle.case.status.replace('_',' ')}</span></div></div>{['draft','needs_info'].includes(bundle.case.status)&&<div className="rounded-2xl border border-white/10 p-5 space-y-4"><label className="text-sm">Evidence type<select value={kind} onChange={e=>setKind(e.target.value)} className="block w-full mt-2 bg-white/5 border border-white/10 rounded-xl p-3"><option value="identity">Identity</option><option value="address">Address</option><option value="selfie">Provider liveness check</option>{bundle.case.caseType==='business'&&<><option value="company">Company</option><option value="ownership">Beneficial ownership</option><option value="authority">Authorised user</option></>}</select></label><label className="text-sm">Approved-provider reference<input value={reference} onChange={e=>setReference(e.target.value)} className="block w-full mt-2 bg-white/5 border border-white/10 rounded-xl p-3" placeholder="provider-case-reference"/></label><button disabled={busy||reference.length<3} onClick={()=>void addEvidence()} className="px-4 py-2 rounded-xl bg-primary text-primary-foreground">Add reference</button></div>}<div className="space-y-2">{bundle.evidence.map(e=><div key={e.id} className="rounded-xl bg-white/5 p-3 flex gap-3"><ShieldCheck className="text-primary"/><div><div className="font-semibold text-sm">{e.kind}</div><div className="text-xs text-foreground/45">{e.reference}</div></div></div>)}</div>{['draft','needs_info'].includes(bundle.case.status)&&<button disabled={busy||bundle.evidence.length===0} onClick={()=>void submit()} className="w-full py-3 rounded-xl bg-emerald-500/20 text-emerald-300 font-semibold">Submit for review</button>}{message&&<p className="rounded-xl border border-white/10 p-3 text-sm flex gap-2"><CheckCircle2 size={16}/>{message}</p>}</>}</div></main>;
}
