export const OPERATIONAL_PROCEDURE_STATUS = 'DRAFT — SPONSOR AND COUNSEL APPROVAL REQUIRED' as const;

const common = `> ${OPERATIONAL_PROCEDURE_STATUS}\n> This procedure does not authorise launch or enable financial operations. Named roles must be assigned to real people and all thresholds, time limits and notification duties must be approved for the final legal entity, sponsor and jurisdiction.\n\n`;

export const OPERATIONAL_PROCEDURES: Record<string, string> = {
  '09-safeguarding-reconciliation-procedure.md': `# Safeguarding and Reconciliation Procedure\n\n${common}## Control objective\n\nProve each business day that sponsor/provider records, safeguarded-account statements and the City Gate read-only sub-ledger agree, and ensure that City Gate never treats its application balance as the authoritative record.\n\n## Daily operation\n\n1. Finance obtains complete, authenticated statements and event files from the sponsor, payment/FX providers and safeguarded accounts. Each input receives a business date, provider statement reference, immutable file hash and ingestion result.\n2. The reconciliation engine matches provider transaction, payment, reversal, fee, FX quote, account and posting-batch identifiers to the internal sub-ledger. No amount is silently netted or changed.\n3. The operator records opening and closing positions, expected safeguarded liability, account balance, in-flight items and every break by currency.\n4. Breaks are classified as timing, missing event, duplicate, amount/currency mismatch, return/reversal, fee, customer allocation or unknown. The sponsor-approved materiality and ageing thresholds determine escalation; no unapproved numeric threshold is embedded here.\n5. A Finance maker investigates and proposes correction. A different authorised checker reviews any correction, write-off, customer-impact action or closure. Ledger history remains append-only.\n6. The completed run records totals, unresolved breaks, evidence hashes, maker, checker, timestamps and sponsor notifications. Regulatory or safeguarding concerns are immediately referred to Compliance under the approved escalation matrix.\n\n## Failure and continuity\n\nIf an authoritative statement is late, incomplete, unsigned or fails integrity checks, the run is marked failed—not passed with estimates. Affected corridors remain unavailable. Finance escalates to the sponsor and Incident Commander, preserves evidence, and reruns from the last verified checkpoint. Real-money activation requires evidence of successful daily runs and exception closure in the controlled pilot.\n`,

  '10-privacy-and-data-rights-procedure.md': `# Privacy, Retention and Data-Rights Procedure\n\n${common}## Control objective\n\nProcess only approved data for documented purposes, retain it for an approved period, and provide an auditable workflow for access, correction, deletion, restriction, objection and portability requests where applicable.\n\n## Data governance\n\n1. The Privacy owner maintains a data inventory covering purpose, lawful basis, categories, source, recipients, processor, location, transfer mechanism, retention rule, security classification and deletion method.\n2. A data-protection impact assessment is completed before high-risk processing, new identity/screening providers, biometrics, systematic monitoring or material purpose changes. Unresolved high risk is a launch blocker.\n3. Processor contracts, subprocessor lists, international transfers and customer notices require recorded review. Production identity documents and provider secrets must not enter the sponsor-readiness evidence register.\n4. Retention and deletion jobs must produce non-sensitive execution evidence and exceptions. Legal holds suspend deletion only for the documented scope and duration.\n\n## Rights request workflow\n\nLog the request, verify identity proportionately, determine applicable rights and deadline, locate data across approved systems, apply exemptions only with documented legal review, conduct a checker review, deliver securely, and record completion. The public response period must come from the approved jurisdictional schedule rather than a UI constant. Complaints and suspected breaches are linked to their controlled cases without copying unnecessary personal data.\n`,

  '11-incident-breach-response-procedure.md': `# Security Incident, Data Breach and Provider-Outage Procedure\n\n${common}## Severity and command\n\nEvery suspected event receives an incident identifier, start/discovery timestamps, affected services/data/providers, current severity, Incident Commander, Security lead, Compliance lead, Communications owner and evidence custodian. Severity is based on customer, funds, confidentiality, integrity, availability, regulatory and systemic impact; an administrator cannot downgrade a material event without a recorded checker decision.\n\n## Response lifecycle\n\n1. Detect and triage without destroying volatile evidence. Record the reporter, signals and initial scope.\n2. Contain using least-disruptive reversible actions. Disable affected corridors or provider credentials where necessary; never manufacture reconciliation or screening results.\n3. Assess personal-data, safeguarding, sanctions, payment, customer and operational-resilience impact. Start jurisdiction- and contract-specific notification clocks from approved matrices.\n4. Notify the sponsor, providers, authorities, insurers and affected customers only through approved decision trees and templates. Record decision owner, legal basis, time and delivery evidence, including a reason when notification is not required.\n5. Eradicate the cause, recover from verified artifacts, reconcile every affected posting/event, monitor for recurrence and obtain business-owner acceptance.\n6. Complete a blameless root-cause review with corrective actions, owners, deadlines and independent closure evidence. Material lessons update risk assessments, procedures, training and the sponsor pack.\n\n## Evidence protection\n\nStore metadata and controlled references in the administration system; keep sensitive forensic artifacts in the approved evidence repository. Preserve hashes, access logs and chain of custody. Incident closure never unlocks financial operations.\n`,

  '12-disaster-recovery-exercise-procedure.md': `# Disaster Recovery and Continuity Exercise Procedure\n\n${common}## Preconditions\n\nThe sponsor and service owners approve important services, dependencies, recovery point objectives, recovery time objectives, impact tolerances, backup retention, restore authority and communications before the exercise. Production restoration is never tested destructively without a separately approved change plan.\n\n## Exercise\n\n1. Define scenario, systems, synthetic dataset, observers, abort criteria and expected recovery checkpoints.\n2. Verify backup provenance, encryption, immutability/retention, access separation and integrity before restore.\n3. Restore into an isolated environment. Record backup point, start/end times, database migration level, secrets/configuration source and every manual intervention.\n4. Validate authentication, role enforcement, audit integrity, customer-record counts, provider-event uniqueness, ledger totals, reconciliation identifiers and the real-funds lock.\n5. Exercise provider outage and loss-of-region communications, escalation and controlled degradation. No synthetic result may be represented as a provider SLA test.\n6. Compare measured data loss and recovery time with approved objectives. Failed objectives, incomplete evidence or unresolved reconciliation produce a failed exercise.\n7. Record findings, owners, due dates, retest evidence and independent acceptance. Only approved evidence metadata is submitted to sponsor readiness.\n`,

  '13-provider-failure-and-exit-procedure.md': `# Provider Failure, Exit and Orderly Wind-Down Procedure\n\n${common}## Control objective\n\nMaintain safe customer support, evidence integrity and sponsor-led continuity when an identity, screening, payment, FX, ledger, hosting or communications provider is unavailable, terminated or insolvent. City Gate must not invent provider results or treat its application records as authoritative during a provider failure.\n\n## Readiness and response\n\n1. Maintain an approved supplier register with service owner, sponsor dependency, data and funds role, subcontractors, concentration risk, recovery commitments, notification duties, audit rights, data portability, termination assistance and exit route.\n2. Define health signals and sponsor-approved triggers for degraded service, corridor suspension, onboarding suspension and incident declaration. Fail closed whenever screening, authoritative ledger, reconciliation or safeguarding inputs are unavailable or unverifiable.\n3. On failure, preserve request, event and reconciliation identifiers; stop unsafe retries; notify the Incident Commander, sponsor and accountable owners; and communicate only approved customer information.\n4. Reconcile every in-flight command against authoritative provider evidence before resuming. Unknown outcomes remain pending or restricted rather than being represented as successful or failed.\n5. For exit, obtain complete export inventories, integrity hashes, retention/deletion attestations, open-case and in-flight-item registers, credential revocation evidence and sponsor acceptance before termination.\n6. Migration to a replacement provider requires due diligence, contract approval, sandbox and negative-path certification, parallel reconciliation, rollback criteria and an independently approved cutover.\n\n## Evidence and testing\n\nExercise at least the sponsor-approved scenarios for prolonged outage, incomplete export, disputed transaction state and supplier insolvency. Record measured recovery, customer impact, reconciliation outcomes, unresolved dependencies and corrective actions. A draft playbook or synthetic rehearsal is not provider operating evidence.\n`,

  '14-returns-reversals-and-remediation-procedure.md': `# Returns, Reversals and Customer Remediation Procedure\n\n${common}## Control objective\n\nProcess rejected, returned, recalled, reversed and duplicated payments from authoritative provider states, with balanced corrective postings, customer communication and reconciliation closure. No administrator may directly edit a customer balance to represent a return or reversal.\n\n## Lifecycle\n\n1. Create each payment command with an idempotency key, customer-visible reference, correlation identifier, corridor, currency, fees and the applicable screening decision.\n2. Accept status changes only from authenticated provider responses or signed, replay-protected events. Preserve provider payment, return, reversal and posting-batch identifiers.\n3. Classify the event under the sponsor-approved state model and determine whether funds are pending, unavailable, returned or subject to investigation. Unknown or conflicting states fail closed and open a reconciliation break.\n4. A reversal or remediation posting must reference the original transaction, use the authoritative amount and currency, balance by currency and remain immutable. Corrections use a new entry rather than changing history.\n5. Apply maker-checker approval for manual remediation, fee waiver, write-off or customer-impacting exception. Record the reason, evidence references, decision makers and customer notification.\n6. Close only after provider, safeguarded-account and ledger evidence agree and any complaint, sanctions or financial-crime case is linked and dispositioned.\n\n## Certification\n\nThe contracted provider must certify duplicate requests, timeout/unknown outcomes, rejected payments, partial information, returns, recalls, reversals, webhook replay, out-of-order events and reconciliation breaks. Synthetic adapter results demonstrate contract shape only and are not production certification.\n`,

  '15-vulnerable-customer-support-procedure.md': `# Vulnerable Customer Support and Outcomes Procedure\n\n${common}## Control objective\n\nProvide accessible, respectful and consistent support for customers whose health, life events, resilience or capability may create additional risk of harm, without making unnecessary assumptions or collecting excessive sensitive data.\n\n## Customer support\n\n1. Make it easy for a customer or authorised representative to disclose a support need through approved channels. Explain what will be recorded, why, who can access it, how long it is retained and how consent or authority is handled.\n2. Record only the minimum functional need and agreed adjustment, using restricted access and a review date. Do not record diagnoses or infer vulnerability when an adjustment can be delivered without them.\n3. Offer approved adjustments such as accessible formats, additional explanation or time, communication preferences, interpreter or representative support, and a safe pause in non-urgent journeys. Never weaken authentication, fraud, sanctions or safeguarding controls.\n4. Escalate signs of coercion, financial abuse, fraud, severe distress, capacity concern or immediate danger under trained decision trees. Emergency or safeguarding referrals require approved legal and operational guidance.\n5. Review complaints, abandonment, repeat contact, service denial, error correction and outcome data for disparate harm. Correct systemic issues through accountable owners and independent closure evidence.\n\n## Governance\n\nThe sponsor and counsel must approve the policy, data fields, access model, training, referral routes, customer wording, quality assurance and outcomes measures. Complete staff training, scenario testing and periodic outcomes review before a controlled consumer pilot.\n`,

  '16-double-entry-ledger-integration-procedure.md': `# Sponsor-Led Double-Entry Ledger Integration Procedure\n\n${common}## Control objective\n\nDefine how City Gate will submit, receive and reconcile financial events while the contracted sponsor/core ledger remains the sole authoritative record. Existing application balances and transactions are demonstration projections and must never be promoted into authoritative opening balances.\n\n## Posting model\n\n1. The sponsor and Finance approve the chart of accounts, currency treatment, posting rules, holds, settlement states, fee and FX legs, suspense accounts and permitted adjustment types before certification.\n2. Every financial event carries an immutable customer reference, idempotency key, correlation identifier, provider event identifier, posting-batch identifier, value date, booking date and currency. Identifier reuse with different input is rejected.\n3. Each journal entry balances debits and credits by currency. Lines are append-only; corrections, reversals and remediation use new linked entries rather than modifying history.\n4. City Gate submits commands only through an approved provider adapter and accepts state changes only from authenticated responses or signed, replay-protected events. Unknown outcomes remain pending and restricted.\n5. The displayed balance is rebuilt from the sponsor/core ledger projection and is labelled unavailable when authoritative events are incomplete, stale or unreconciled. Browser calculations and direct administrative balance editing are prohibited.\n6. Daily reconciliation proves provider commands, webhook events, ledger postings, safeguarded-account statements and customer projections agree. Breaks follow the approved maker-checker escalation procedure.\n\n## Certification and migration\n\nCertification must cover duplicates, concurrency, timeouts, out-of-order events, multi-currency postings, fees, FX, rejected payments, returns, reversals, suspense handling and restart recovery. Migration requires sponsor-approved opening positions, hash-backed source totals, parallel reconciliation, rollback criteria and independent sign-off. The synthetic provider adapter proves contract shape only and is not a live ledger or certification result.\n`,

  '17-cross-border-data-transfer-mapping-procedure.md': `# Cross-Border Data Transfer Mapping Procedure\n\n${common}## Control objective\n\nMaintain an evidence-backed map of every approved system and provider that stores, receives or permits remote access to personal data, so no international transfer or onward transfer occurs without documented necessity, lawful basis, contractual safeguards and risk assessment.\n\n## Transfer register\n\n1. Record the business purpose, data subjects, data categories, special-category or criminal-offence data, source, controller/processor role, recipient, subprocessor, storage location, support-access location, transit path, retention and deletion method.\n2. Distinguish storage from remote access and onward transfer. Record the legal entities involved rather than relying on product brand names or a provider's general region label.\n3. For each restricted transfer, record the approved transfer mechanism, transfer-risk assessment, supplementary technical and organisational measures, government-access analysis, review date and accountable owner.\n4. Link processor agreements, subprocessor notices, security reviews and customer notices by controlled reference and SHA-256 metadata; do not place contracts or personal data in the sponsor workspace.\n5. Block production adoption when a provider, location, subprocessor, access path or transfer mechanism is unknown, inconsistent or unapproved. Material changes trigger privacy, security, sponsor and counsel review before use.\n6. Reconcile the register periodically against deployed infrastructure, vendor inventories, access logs, data flows and deletion evidence. Exceptions receive owners, deadlines and independent closure.\n\n## Approval boundary\n\nThis procedure is a mapping method, not a completed transfer assessment. The production register must name every processor, subprocessor and location, and the DPO/privacy counsel and sponsor must approve the applicable safeguards before customer data is processed.\n`,

  '18-business-kyb-and-ownership-procedure.md': `# Business KYB, Ownership and Authorised-User Procedure\n\n${common}## Control objective\n\nOnboard only sponsor-approved business types and jurisdictions after verifying the legal person, ownership and control structure, purpose and expected activity, authorised users and relevant financial-crime risks through contracted providers and documented review.\n\n## Onboarding workflow\n\n1. Capture the registered and trading names, entity type, incorporation number, jurisdiction, registered and operating addresses, business activity, purpose of account, expected volumes/corridors and source of funds using approved data fields.\n2. Verify legal existence and status against authoritative registries or contracted data sources. Conflicts, inactive entities, opaque structures and unsupported jurisdictions fail closed into manual review.\n3. Identify beneficial owners and controllers under sponsor-approved thresholds and rules. Trace intermediate entities to natural persons, record ownership/control basis, and verify required persons without storing identity documents in the sponsor-readiness workspace.\n4. Verify directors, account signatories and authorised users; record mandates, permission scope, approval rules and revocation. Customer-supplied role or ownership claims are never accepted as proof of authority.\n5. Apply sponsor-approved sanctions, PEP, adverse-media, fraud and business-risk checks to the entity and relevant persons. Enhanced due diligence, source-of-wealth/funds review and senior approval follow the approved risk model.\n6. A Compliance maker assembles the case and recommendation. An independently authorised checker decides approval, rejection or information request and records rationale, evidence references and review dates.\n7. Continuing review responds to expiry, registry change, ownership/control change, new authorised users, risk events, monitoring alerts and periodic review schedules. Material unresolved changes restrict the account.\n\n## Activation boundary\n\nKYB approval does not create a live account or enable payments. Business onboarding remains out of scope until Phase 3 and requires sponsor approval, contracted provider certification, an approved AML risk assessment, named compliance ownership and successful operating evidence.\n`,

  '19-enterprise-aml-risk-assessment-procedure.md': `# Enterprise AML Risk-Assessment Procedure\n\n${common}## Control objective\n\nEstablish a documented, evidence-based assessment of inherent and residual money-laundering, terrorist-financing, proliferation-financing and related financial-crime risks before defining customers, products, currencies, channels, geographies or corridors as eligible.\n\n## Assessment method\n\n1. Define the proposed legal entity, sponsor model, customers, products, delivery channels, transaction types, currencies, countries, intermediaries and providers. Unknown or proposed scope is recorded as a gap, not assigned a reassuring score.\n2. Use approved external and internal sources to assess each risk dimension, including typologies, sanctions exposure, customer opacity, ownership complexity, non-face-to-face delivery, payment velocity, cross-border activity and provider dependency. Record source, date, relevance and limitations.\n3. Define sponsor-approved scoring scales, weightings and aggregation rules before scoring. Overrides require a reason, evidence, accountable maker and independent checker; the system must preserve the original and resulting assessment.\n4. Map each inherent risk to implemented controls, control owner, design evidence, operating evidence, testing result and deficiency. A draft policy, UI control or synthetic result does not reduce residual risk without approved operating evidence.\n5. Record residual risks, risk-appetite comparison, prohibited or restricted segments, enhanced controls, remediation owners and deadlines. Risks above appetite block the affected product, customer class or corridor.\n6. The qualified MLRO and sponsor approve the assessment and report material conclusions to the governing body. Review is triggered by material product, provider, geography, typology, regulatory or performance change and at the approved periodic interval.\n\n## Evidence boundary\n\nThis document defines a method; it is not a completed enterprise risk assessment. No production scope, score, risk appetite, MLRO decision or sponsor approval may be inferred from it.\n`,

  '20-transaction-monitoring-governance-procedure.md': `# Transaction-Monitoring Governance Procedure\n\n${common}## Control objective\n\nDetect, investigate and escalate suspicious or prohibited activity from complete authoritative transaction and customer-risk data, while preserving explainability, case history, confidentiality and sponsor/MLRO accountability. No production transaction-monitoring programme is active in this environment.\n\n## Programme design\n\n1. Inventory authoritative inputs for customers, beneficial owners, accounts, beneficiaries, devices, counterparties, payments, FX, returns, reversals, sanctions events and ledger postings. Missing, stale or irreconcilable mandatory feeds block the affected corridor.\n2. Derive scenarios from the approved enterprise risk assessment and sponsor typologies. Each scenario records purpose, population, data fields, logic, threshold rationale, exclusions, severity, owner, version and effective dates; administrators cannot silently alter thresholds.\n3. Validate data completeness, scenario implementation, alert generation, duplicate handling and expected positive/negative cases before activation. Material changes require maker-checker approval, regression testing and documented back-testing where appropriate.\n4. Route alerts to restricted, immutable cases with customer and transaction references, risk context, evidence, investigator actions, decisions and timestamps. Clearing an alert cannot manufacture a provider screening result or modify transaction history.\n5. Escalation to the qualified MLRO follows approved triage and confidentiality rules. Suspicious-activity reporting, consent/defence requests, law-enforcement interaction, account restriction and customer communication use jurisdiction-specific approved procedures; the application must not expose sensitive reporting status to customers.\n6. Measure feed health, alert volumes, ageing, dispositions, investigator quality, false negatives/positives, scenario coverage and remediation. Independent quality assurance and periodic effectiveness review feed back into the risk assessment.\n\n## Activation boundary\n\nThe existing compliance queue and synthetic events demonstrate workflow structure only. Launch requires contracted provider capability, authoritative feeds, approved scenarios and thresholds, qualified investigators and MLRO, validated filing procedures, independent testing and sustained operating evidence.\n`,

  '21-customer-terms-and-disclosure-approval-procedure.md': `# Customer Terms and Product-Disclosure Approval Procedure\n\n${common}## Control objective\n\nEnsure every public claim, contractual term, fee, FX disclosure, funds-protection statement and customer communication accurately reflects the final legal entity, sponsor, provider, jurisdiction, product and operating capability before publication or acceptance.\n\n## Controlled content lifecycle\n\n1. Maintain a register of required documents and disclosures by audience, product, jurisdiction, channel and journey. Assign legal, compliance, product and sponsor approvers and record dependencies such as provider names, permissions, safeguarding structure, complaints route, fees and service limits.\n2. Draft in plain language with version, effective date, owner and controlled source. Unresolved placeholders, unsupported claims, contradictory pages or unknown commercial terms prevent approval. Existing pre-deployment terms are not suitable for live financial services.\n3. Verify consistency across the website, registration, dashboards, quotes, confirmations, receipts, email, support scripts and accessibility formats. Product controls and feature flags must match the approved wording and cannot enable a capability absent from the terms.\n4. Compliance and counsel review legal accuracy, consumer outcomes and prominence; Finance verifies fees, FX and protection wording; Security/Privacy verify data statements. The sponsor gives final programme approval through an independent recorded decision.\n5. Publish only the approved immutable version and record SHA-256, effective time and channels. Capture the version accepted by each customer and provide durable access; material changes follow approved notice and renewed-consent rules.\n6. Monitor complaints, abandonment, misunderstanding, accessibility and customer outcomes. Emergency corrections preserve prior versions, decision history and affected-customer analysis.\n\n## Approval boundary\n\nThis workflow does not approve current public wording. Final live terms require the verified legal entity, contracted sponsor/providers, confirmed permissions and protection structure, approved commercial schedules, jurisdiction-specific redress and completed customer-outcomes testing.\n`,
  '22-sponsor-provider-responsibility-matrix.md': `# Sponsor, City Gate and Provider Responsibility Matrix

${common}## Control objective

Assign every regulated, operational and technical duty to an accountable legal entity and named role before contracting or launch, and prevent gaps or duplicated assumptions between the sponsor, City Gate and specialist providers.

## Matrix lifecycle

1. Catalogue each activity covering permissions, customer terms, safeguarding, onboarding, screening, monitoring, complaints, funds movement, FX, ledger, reconciliation, fraud, security, privacy, resilience, reporting, audit, support, wind-down and regulatory interaction.
2. For every activity record the accountable legal entity, responsible operator, consulted parties, evidence producer, decision authority, escalation owner, service level and contract clause. A product brand or software component is not an accountable legal entity.
3. Reconcile the matrix against provider contracts, operating procedures, data flows, customer disclosures, incident plans and regulatory submissions. Conflicts and unassigned duties block the affected phase.
4. Require maker-checker approval for changes and preserve version, effective date, rationale and prior allocation. Material provider, product, corridor or regulatory changes trigger renewed sponsor and counsel review.
5. Test the matrix through onboarding, screening outage, payment unknown-state, safeguarding break, complaint, data breach and wind-down scenarios. Record unresolved decisions and corrective owners.

## Approval boundary

This document is a draft allocation method. It does not name or bind a sponsor or provider and is not an executed responsibility schedule. Final approval requires the contracted parties, accountable people and consistent contract evidence.
`,

  '23-safeguarding-structure-and-assurance-plan.md': `# Safeguarding Structure and Independent Assurance Plan

${common}## Structure decision

1. The authorised sponsor and qualified counsel determine which safeguarding regime applies, who receives customer funds, the account and trust/segregation structure, acknowledgement requirements, permitted diversification and insolvency treatment.
2. Finance maps each receipt, pending item, fee, FX conversion, payout, return and reversal to the safeguarding calculation and authoritative ledger. City Gate never receives or controls funds outside the approved structure.
3. Document the daily calculation, timing cut-offs, currency treatment, unmatched items, access controls, signatories, provider statements, reconciliation dependencies and break escalation. Unknown treatment blocks the product or corridor.
4. Obtain executed account evidence and sponsor approval before any customer funding instruction is displayed. Public wording must match the approved legal structure and must not imply deposit insurance or bank-account status without verified entitlement.

## Assurance plan

Define the applicable independent assurance or audit scope, reviewer qualifications, frequency, evidence access, sampling, deficiency rating, sponsor reporting, remediation and governing-body oversight. Operating evidence includes completed calculations, reconciliations, break closure, access reviews and tested insolvency/wind-down scenarios. A procedure or synthetic test is design evidence only.

## Activation boundary

No safeguarding structure, account, reviewer or assurance conclusion is approved by this draft. Customer funds and funding instructions remain unavailable until the authorised sponsor and counsel approve the complete structure and operating evidence.
`,

  '24-identity-screening-provider-due-diligence.md': `# Identity and Screening Provider Due-Diligence Procedure

${common}## Evaluation register

For each candidate, record the contracting legal entity, regulated and geographic coverage, identity sources, document/biometric assurance, sanctions/PEP/adverse-media lists, refresh cadence, rescreening triggers, matching behavior, manual review, explainability, fraud controls, data locations, subprocessors, retention, security assurance, resilience, audit rights, service levels, exit support and pricing.

## Validation

1. Compliance defines approved populations, documents, jurisdictions, risk levels and prohibited gaps from the enterprise risk assessment and sponsor policy.
2. Privacy and Security complete data-flow, DPIA, transfer, access, encryption, incident and deletion reviews before production data is supplied.
3. Test representative positive, negative, ambiguous, duplicate, expired, tampered, transliterated and accessibility cases with synthetic data. Screening tests cover list freshness, aliases, fuzzy matching, false positives, rescreening and outage behavior.
4. Validate signed event delivery, idempotency, correlation, replay protection, manual overrides, audit exports and evidence retention. Provider unavailability or unverifiable results fail closed.
5. Record residual gaps, compensating controls, owner, deadline and independent approval. Contract execution does not replace sponsor/MLRO acceptance or operating validation.

## Approval boundary

This procedure does not select, endorse or connect a provider. Production onboarding and screening require contracted providers, verified capability, completed diligence, certified integration and sponsor/MLRO approval.
`,

  '25-compliance-officer-mandate.md': `# Compliance Officer and MLRO Mandate

${common}## Role design

The governing body and sponsor must appoint suitably qualified named individuals with documented authority, independence, direct escalation access, adequate resources, information access, confidentiality protections and authority to restrict onboarding, products, customers and transactions. Required regulatory approval or notification must be completed before the appointment is represented as effective.

## Responsibilities

1. Own the enterprise financial-crime risk assessment, policies, risk appetite, customer and corridor eligibility, enhanced due diligence and continuing review.
2. Oversee sanctions/PEP/adverse-media screening, transaction monitoring, investigation quality, suspicious-activity escalation, reporting and prohibited customer disclosure.
3. Report material risks, breaches, backlogs, control performance and remediation to the governing body and sponsor without management filtering.
4. Approve competent deputies, absence cover, conflicts management, training, quality assurance and record retention. Administrators cannot appoint themselves by changing a setting.
5. Maintain fit-and-proper, experience, capacity, training, appointment, reporting-line and periodic effectiveness evidence through controlled references.

## Approval boundary

This draft defines a mandate, not a person. No compliance officer or MLRO is appointed until identity, competence, authority, capacity, reporting line and sponsor/regulatory acceptance are independently evidenced.
`,

  '26-fx-and-payment-corridor-governance.md': `# Provider-Executed FX and Payment-Corridor Governance

${common}## Provider-authoritative FX

1. A contracted provider returns quote ID, source/target currencies, amounts, rate, spread, fees, expiry, settlement conditions and execution eligibility. City Gate does not manufacture live prices or execution results.
2. The customer receives the complete approved disclosure before confirmation. Expired or changed quotes require renewed consent; unknown execution states remain pending and restricted.
3. Commands use idempotency and correlation identifiers. State changes require authenticated responses or signed replay-protected events and reconcile to provider and ledger identifiers.

## Corridor register

For each origin/destination, currency, rail, customer type and use case, record sponsor/provider availability, permissions, sanctions and AML assessment, beneficiary/data requirements, limits, cut-offs, fees, returns/reversals, safeguarding and settlement treatment, reconciliation mapping, customer terms, support, complaints, testing, effective dates and approvers. Approval is corridor-specific and does not inherit from another rail or currency.

## Change and suspension

Pricing, provider, sanctions, data, settlement or performance changes trigger impact review and maker-checker approval. Missing screening, stale quote, provider outage, unreconciled break or expired approval suspends only the affected scope and records customer-impact handling.

## Activation boundary

No provider, price, currency or corridor is approved by this document. Production activation requires executed contracts, sponsor approval, certified integration, final disclosures and sustained reconciliation evidence.
`,

  '27-independent-penetration-test-plan.md': `# Independent Penetration-Test and Remediation Plan

${common}## Scope and independence

Security defines internet-facing applications, APIs, authentication, customer and administrator authorization, sessions, uploads, webhooks, cloud configuration, network boundaries and relevant mobile/provider interfaces. A qualified independent tester confirms rules of engagement, credentials, data handling, exclusions, safe-testing windows, incident contacts and retest terms. Exclusions require risk-owner and sponsor acceptance.

## Required coverage

Test OWASP-class weaknesses, business-logic abuse, IDOR/BOLA, privilege escalation, customer/admin separation, maker-checker bypass, account recovery, MFA, CSRF, XSS, injection, SSRF, file handling, rate limits, webhook authentication/replay, secrets exposure, logging and cloud misconfiguration. Financial tests must prove locked operations cannot be enabled through client input, evidence approval or administrator override.

## Findings and closure

Record severity, exploit evidence, affected asset/version, owner, target date, compensating controls and release impact without placing sensitive exploit material in the sponsor workspace. Critical/high findings and systemic authorization defects block launch. Closure requires remediation, regression tests, independent retest and security/sponsor acceptance; risk acceptance requires accountable rationale and expiry.

## Approval boundary

This is a test plan, not a penetration-test report. No assurance conclusion exists until an independent test, remediation and retest have been completed and approved against the production release scope.
`,

  '28-customer-funds-wording-approval.md': `# Customer-Funds and Safeguarding Wording Approval

${common}## Claim register

Inventory every statement about accounts, deposits, safeguarding, segregation, custody, ownership, availability, settlement, insolvency, compensation, insurance, issuer/sponsor identity, regulated status and complaints/redress across the website, registration, dashboard, funding instructions, confirmations, receipts, support and email.

## Approval workflow

1. Link each claim to the verified legal entity, sponsor contract, permissions analysis, safeguarding structure, account evidence, product terms and operational capability.
2. Compliance and counsel verify legal accuracy and prominence; Finance verifies funds flow and reconciliation; Product confirms the interface cannot contradict the wording; the sponsor gives final programme approval.
3. Prohibit unsupported use of bank, bank account, deposit, insured, protected, guaranteed, custodian or equivalent language. Explain material differences between safeguarding and deposit protection in approved plain language.
4. Test comprehension and accessibility with the target audience. Record version, hash, channels, effective date and customer acceptance; preserve prior versions and change notices.
5. Monitor complaints, misunderstanding and service changes. A material change suspends affected claims until reapproved.

## Approval boundary

Current wording describes unavailable services and sample data. This workflow does not approve live customer-funds claims. Final wording requires the confirmed legal entity, sponsor, safeguarding structure, permissions, redress route and independently approved evidence.
`,
};
