import crypto from 'node:crypto';
import { getQueryClient,isDatabaseConfigured } from '../db/db.js';
import { appendAuditEntry } from './auditLog.js';
import { financialSandbox } from './financialSandboxStore.js';
import type { SandboxActor } from './financialSandbox.js';
import { findTransactionById } from './transactionStore.js';

export type DisputeStatus='open'|'investigating'|'escalated'|'remediation_pending'|'resolved'|'rejected'|'closed';
export type DisputeActor=SandboxActor&{actorType:'admin'|'independent_checker'|'system'|'customer'};
export type DisputeEvidence={id:string;caseId:string;label:string;controlledReference:string;evidenceSha256:string;addedBy:string;createdAt:string};
export type DisputeNotification={id:string;caseId:string;channel:'in_app'|'email'|'letter'|'phone';subject:string;message:string;deliveryStatus:'recorded'|'queued'|'sent'|'failed';providerReference?:string;recordedBy:string;createdAt:string};
export type DisputeEvent={id:string;caseId:string;action:string;actorId:string;actorType:DisputeActor['actorType'];fromStatus?:string;toStatus:string;rationale:string;correlationId:string;details:Record<string,unknown>;createdAt:string};
export type DisputeCase={id:string;reference:string;caseType:'customer_dispute'|'payment_error';category:string;priority:'low'|'medium'|'high'|'critical';status:DisputeStatus;customerReference:string;customerUserId?:string;customerIdempotencyKey?:string;transactionId?:string;transferId?:string;monitoringAlertId?:string;reconciliationExceptionId?:string;summary:string;customerClaim:string;owner?:string;investigationNotes?:string;dueAt:string;escalatedAt?:string;remediationType?:'full_refund'|'full_reversal'|'no_financial_action';remediationReason?:string;remediationTransactionId?:string;submittedBy?:string;submittedAt?:string;reviewedBy?:string;reviewedAt?:string;checkerNote?:string;lastEditedBy:string;caseSha256:string;createdAt:string;updatedAt:string;evidence:DisputeEvidence[];notifications:DisputeNotification[];events:DisputeEvent[];ageingDays:number;overdue:boolean;synthetic:true};

export class SyntheticDisputeError extends Error{constructor(message:string,public readonly code:string,public readonly status=400){super(message);}}
const localCases=new Map<string,DisputeCase>();
const text=(value:unknown,label:string,min=1,max=1000)=>{const clean=String(value??'').trim();if(clean.length<min||clean.length>max)throw new SyntheticDisputeError(`${label} must contain ${min}-${max} characters.`,'VALIDATION_ERROR');return clean;};
const optional=(value:unknown,prefix:string,label:string)=>{const clean=String(value??'').trim();if(!clean)return undefined;if(!clean.startsWith(prefix))throw new SyntheticDisputeError(`${label} must be a synthetic reference.`,'SYNTHETIC_REFERENCE_REQUIRED');return clean;};
const hash=(value:unknown)=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
const days=(iso:string)=>Math.max(0,Math.floor((Date.now()-new Date(iso).getTime())/86400000));
const db=()=>process.env.NODE_ENV==='production'||isDatabaseConfigured();
const iso=(value:unknown)=>value?new Date(value as string|number|Date).toISOString():undefined;
async function audit(actor:DisputeActor,action:string,targetId:string,details:Record<string,unknown>={}){await appendAuditEntry({adminId:actor.id,adminEmail:actor.email,action,target:'synthetic-dispute',targetId,ip:actor.ip,details:{...details,synthetic:true,financialOperationsLocked:true,correlationId:actor.correlationId}});}

function enrich(item:Omit<DisputeCase,'ageingDays'|'overdue'>):DisputeCase{return {...item,ageingDays:days(item.createdAt),overdue:!['resolved','rejected','closed'].includes(item.status)&&new Date(item.dueAt).getTime()<Date.now()};}
async function databaseList():Promise<DisputeCase[]>{
  const sql=getQueryClient();
  const rows=await sql<any[]>`SELECT * FROM synthetic_dispute_cases ORDER BY updated_at DESC LIMIT 1000`;
  const output:DisputeCase[]=[];
  for(const row of rows){
    const evidence=await sql<any[]>`SELECT * FROM synthetic_dispute_evidence WHERE case_id=${row.id} ORDER BY created_at,id`;
    const notifications=await sql<any[]>`SELECT * FROM synthetic_dispute_notifications WHERE case_id=${row.id} ORDER BY created_at,id`;
    const events=await sql<any[]>`SELECT * FROM synthetic_dispute_events WHERE case_id=${row.id} ORDER BY created_at,id`;
    output.push(enrich({id:row.id,reference:row.reference,caseType:row.case_type,category:row.category,priority:row.priority,status:row.status,customerReference:row.customer_reference,customerUserId:row.customer_user_id??undefined,customerIdempotencyKey:row.customer_idempotency_key??undefined,transactionId:row.transaction_id??undefined,transferId:row.transfer_id??undefined,monitoringAlertId:row.monitoring_alert_id??undefined,reconciliationExceptionId:row.reconciliation_exception_id??undefined,summary:row.summary,customerClaim:row.customer_claim,owner:row.owner??undefined,investigationNotes:row.investigation_notes??undefined,dueAt:iso(row.due_at)!,escalatedAt:iso(row.escalated_at),remediationType:row.remediation_type??undefined,remediationReason:row.remediation_reason??undefined,remediationTransactionId:row.remediation_transaction_id??undefined,submittedBy:row.submitted_by??undefined,submittedAt:iso(row.submitted_at),reviewedBy:row.reviewed_by??undefined,reviewedAt:iso(row.reviewed_at),checkerNote:row.checker_note??undefined,lastEditedBy:row.last_edited_by,caseSha256:row.case_sha256,createdAt:iso(row.created_at)!,updatedAt:iso(row.updated_at)!,synthetic:true,evidence:evidence.map((e:any)=>({id:e.id,caseId:e.case_id,label:e.label,controlledReference:e.controlled_reference,evidenceSha256:e.evidence_sha256,addedBy:e.added_by,createdAt:iso(e.created_at)!})),notifications:notifications.map((n:any)=>({id:n.id,caseId:n.case_id,channel:n.channel,subject:n.subject,message:n.message,deliveryStatus:n.delivery_status,providerReference:n.provider_reference??undefined,recordedBy:n.recorded_by,createdAt:iso(n.created_at)!})),events:events.map((e:any)=>({id:e.id,caseId:e.case_id,action:e.action,actorId:e.actor_id,actorType:e.actor_type,fromStatus:e.from_status??undefined,toStatus:e.to_status,rationale:e.rationale,correlationId:e.request_correlation_id,details:e.details??{},createdAt:iso(e.created_at)!}))}));
  }
  return output;
}
async function find(id:string){if(!id.startsWith('syn_dispute_'))throw new SyntheticDisputeError('Dispute case not found.','NOT_FOUND',404);const item=(db()?await databaseList():[...localCases.values()]).find(value=>value.id===id);if(!item)throw new SyntheticDisputeError('Dispute case not found.','NOT_FOUND',404);return item;}
async function addEvent(item:DisputeCase,event:DisputeEvent){item.events.push(event);if(db())await getQueryClient()`INSERT INTO synthetic_dispute_events (id,case_id,action,actor_id,actor_type,from_status,to_status,rationale,request_correlation_id,details) VALUES (${event.id},${event.caseId},${event.action},${event.actorId},${event.actorType},${event.fromStatus??null},${event.toStatus},${event.rationale},${event.correlationId},${getQueryClient().json(JSON.parse(JSON.stringify(event.details)))})`;}

export const syntheticDisputes={
  resetForTests(){localCases.clear();},
  async list(){const cases=db()?await databaseList():[...localCases.values()].map(item=>enrich(item));return {cases,overview:{open:cases.filter(x=>!['resolved','rejected','closed'].includes(x.status)).length,overdue:cases.filter(x=>x.overdue).length,escalated:cases.filter(x=>x.status==='escalated').length,pendingApproval:cases.filter(x=>x.status==='remediation_pending').length,resolved:cases.filter(x=>x.status==='resolved').length,financialOperationsLocked:true as const,liveProviderAdaptersImplemented:false as const}};},
  async listForCustomer(customerUserId:string){
    const cases=(db()?await databaseList():[...localCases.values()].map(item=>enrich(item))).filter(item=>item.customerUserId===customerUserId);
    return cases.map(item=>({
      id:item.id,reference:item.reference,category:item.category,status:item.status,priority:item.priority,
      transactionId:item.transactionId,summary:item.summary,customerClaim:item.customerClaim,dueAt:item.dueAt,
      createdAt:item.createdAt,updatedAt:item.updatedAt,overdue:item.overdue,
      timeline:item.events.map(event=>({action:event.action,status:event.toStatus,createdAt:event.createdAt})),
      notifications:item.notifications.filter(note=>note.channel==='in_app').map(note=>({id:note.id,subject:note.subject,message:note.message,createdAt:note.createdAt})),
    }));
  },
  async createForCustomer(input:{transactionId:unknown;category:unknown;claim:unknown;idempotencyKey:unknown},customer:{id:string;email:string},actor:DisputeActor){
    if(actor.actorType!=='customer'||actor.id!==customer.id)throw new SyntheticDisputeError('Customer authentication is required.','CUSTOMER_REQUIRED',403);
    const idempotencyKey=String(input.idempotencyKey??'').trim();
    if(!/^[A-Za-z0-9][A-Za-z0-9._:-]{15,127}$/.test(idempotencyKey))throw new SyntheticDisputeError('A valid idempotency key is required.','IDEMPOTENCY_KEY_REQUIRED');
    const all=db()?await databaseList():[...localCases.values()].map(item=>enrich(item));
    const prior=all.find(item=>item.customerUserId===customer.id&&item.customerIdempotencyKey===idempotencyKey);
    if(prior)return {case:prior,replayed:true};
    const transactionId=text(input.transactionId,'Transaction',3,160);
    const transaction=await findTransactionById(transactionId);
    if(!transaction||transaction.userId!==customer.id)throw new SyntheticDisputeError('Transaction not found.','TRANSACTION_NOT_FOUND',404);
    if(transaction.dataClassification==='synthetic_quarantined')throw new SyntheticDisputeError('This transaction is unavailable for customer claims.','TRANSACTION_UNAVAILABLE',409);
    const allowedCategories=['duplicate','cash_not_received','incorrect_amount','unauthorised','service_not_received','other'];
    const category=String(input.category??'');
    if(!allowedCategories.includes(category))throw new SyntheticDisputeError('Dispute category is invalid.','VALIDATION_ERROR');
    const customerClaim=text(input.claim,'Claim details',20,2000);
    const priority:DisputeCase['priority']=category==='unauthorised'?'high':category==='cash_not_received'?'high':'medium';
    const now=new Date().toISOString(),id=`syn_dispute_${crypto.randomUUID()}`;
    const customerReference=`syn_customer_${hash(customer.id).slice(0,24)}`;
    const dueAt=new Date(Date.now()+14*86400000).toISOString();
    const base={id,reference:`SYN-DSP-${crypto.randomBytes(5).toString('hex').toUpperCase()}`,caseType:'customer_dispute' as const,category,priority,status:'open' as const,customerReference,customerUserId:customer.id,customerIdempotencyKey:idempotencyKey,transactionId:transaction.id,summary:`Customer dispute for transaction ${transaction.reference}`,customerClaim,dueAt,lastEditedBy:customer.id,createdAt:now,updatedAt:now,synthetic:true as const,evidence:[],notifications:[],events:[]};
    const item=enrich({...base,caseSha256:hash(base)});
    const event:DisputeEvent={id:`syn_dispute_event_${crypto.randomUUID()}`,caseId:id,action:'customer_claim_submitted',actorId:customer.id,actorType:'customer',toStatus:'open',rationale:'Customer submitted a transaction dispute.',correlationId:actor.correlationId,details:{caseSha256:item.caseSha256,transactionId:transaction.id,transactionReference:transaction.reference},createdAt:now};
    const notification:DisputeNotification={id:`syn_dispute_notification_${crypto.randomUUID()}`,caseId:id,channel:'in_app',subject:'Dispute received',message:`Your dispute ${item.reference} has been received and is awaiting review.`,deliveryStatus:'recorded',recordedBy:'system',createdAt:now};
    item.events.push(event);item.notifications.push(notification);
    if(db()){
      const sql=getQueryClient();
      try{
        await sql.begin(async tx=>{
          await tx`SELECT pg_advisory_xact_lock(hashtext(${`${customer.id}:${idempotencyKey}`}))`;
          await tx`INSERT INTO synthetic_dispute_cases (id,reference,case_type,category,priority,status,customer_reference,customer_user_id,customer_idempotency_key,transaction_id,summary,customer_claim,due_at,last_edited_by,case_sha256) VALUES (${id},${item.reference},'customer_dispute',${category},${priority},'open',${customerReference},${customer.id},${idempotencyKey},${transaction.id},${item.summary},${customerClaim},${dueAt},${customer.id},${item.caseSha256})`;
          await tx`INSERT INTO synthetic_dispute_events (id,case_id,action,actor_id,actor_type,to_status,rationale,request_correlation_id,details) VALUES (${event.id},${id},${event.action},${customer.id},'customer','open',${event.rationale},${event.correlationId},${tx.json(JSON.parse(JSON.stringify(event.details)))})`;
          await tx`INSERT INTO synthetic_dispute_notifications (id,case_id,channel,subject,message,delivery_status,recorded_by) VALUES (${notification.id},${id},'in_app',${notification.subject},${notification.message},'recorded','system')`;
        });
      }catch(error){
        if((error as {code?:string}).code==='23505'){
          const replay=(await databaseList()).find(existing=>existing.customerUserId===customer.id&&existing.customerIdempotencyKey===idempotencyKey);
          if(replay)return {case:replay,replayed:true};
        }
        throw error;
      }
    }else localCases.set(id,item);
    await audit(actor,'customer_dispute_submitted',id,{reference:item.reference,transactionId:transaction.id,caseSha256:item.caseSha256});
    return {case:item,replayed:false};
  },
  async create(input:Record<string,unknown>,actor:DisputeActor){
    if(actor.actorType!=='admin')throw new SyntheticDisputeError('Administrator authentication is required.','ADMIN_REQUIRED',403);
    const caseType=String(input.caseType) as DisputeCase['caseType'];if(caseType!=='customer_dispute'&&caseType!=='payment_error')throw new SyntheticDisputeError('Case type is invalid.','VALIDATION_ERROR');
    const priority=String(input.priority);if(!['low','medium','high','critical'].includes(priority))throw new SyntheticDisputeError('Priority is invalid.','VALIDATION_ERROR');
    const dueAt=new Date(String(input.dueAt??''));if(!Number.isFinite(dueAt.getTime())||dueAt.getTime()<=Date.now())throw new SyntheticDisputeError('Investigation deadline must be in the future.','VALIDATION_ERROR');
    const now=new Date().toISOString(),id=`syn_dispute_${crypto.randomUUID()}`;
    const base={id,reference:`SYN-DSP-${crypto.randomBytes(5).toString('hex').toUpperCase()}`,caseType,category:text(input.category,'Category',3,80),priority:priority as DisputeCase['priority'],status:'open' as const,customerReference:optional(input.customerReference,'syn_','Customer reference')??(()=>{throw new SyntheticDisputeError('Customer reference is required.','VALIDATION_ERROR');})(),transactionId:optional(input.transactionId,'syn_tx_','Transaction'),transferId:optional(input.transferId,'syn_','Transfer'),monitoringAlertId:optional(input.monitoringAlertId,'syn_alert_','Monitoring alert'),reconciliationExceptionId:optional(input.reconciliationExceptionId,'syn_recon_exception_','Reconciliation exception'),summary:text(input.summary,'Summary',10,240),customerClaim:text(input.customerClaim,'Customer claim',10,2000),dueAt:dueAt.toISOString(),lastEditedBy:actor.id,createdAt:now,updatedAt:now,synthetic:true as const,evidence:[],notifications:[],events:[]};
    const item=enrich({...base,caseSha256:hash(base)});
    const event:DisputeEvent={id:`syn_dispute_event_${crypto.randomUUID()}`,caseId:id,action:'case_opened',actorId:actor.id,actorType:'admin',toStatus:'open',rationale:item.summary,correlationId:actor.correlationId,details:{caseSha256:item.caseSha256,links:{transactionId:item.transactionId,transferId:item.transferId,monitoringAlertId:item.monitoringAlertId,reconciliationExceptionId:item.reconciliationExceptionId}},createdAt:now};
    item.events.push(event);
    if(db()){const sql=getQueryClient();await sql.begin(async tx=>{await tx`INSERT INTO synthetic_dispute_cases (id,reference,case_type,category,priority,status,customer_reference,transaction_id,transfer_id,monitoring_alert_id,reconciliation_exception_id,summary,customer_claim,due_at,last_edited_by,case_sha256) VALUES (${id},${item.reference},${caseType},${item.category},${item.priority},'open',${item.customerReference},${item.transactionId??null},${item.transferId??null},${item.monitoringAlertId??null},${item.reconciliationExceptionId??null},${item.summary},${item.customerClaim},${item.dueAt},${actor.id},${item.caseSha256})`;await tx`INSERT INTO synthetic_dispute_events (id,case_id,action,actor_id,actor_type,to_status,rationale,request_correlation_id,details) VALUES (${event.id},${id},${event.action},${actor.id},'admin','open',${event.rationale},${event.correlationId},${tx.json(JSON.parse(JSON.stringify(event.details)))})`;});}else localCases.set(id,item);
    await audit(actor,'synthetic_dispute_opened',id,{reference:item.reference,caseSha256:item.caseSha256});return item;
  },
  async investigate(id:string,input:{owner:unknown;notes:unknown;escalate?:boolean},actor:DisputeActor){const item=await find(id);if(!['open','investigating','escalated'].includes(item.status))throw new SyntheticDisputeError('Case cannot be edited in its current state.','INVALID_TRANSITION',409);const owner=text(input.owner,'Owner',3,120),notes=text(input.notes,'Investigation notes',10,1500),from=item.status,to:DisputeStatus=input.escalate?'escalated':'investigating',now=new Date().toISOString();Object.assign(item,{owner,investigationNotes:notes,status:to,escalatedAt:input.escalate?now:item.escalatedAt,lastEditedBy:actor.id,updatedAt:now});if(db())await getQueryClient()`UPDATE synthetic_dispute_cases SET status=${to},owner=${owner},investigation_notes=${notes},escalated_at=${input.escalate?now:item.escalatedAt??null},last_edited_by=${actor.id},updated_at=NOW() WHERE id=${id}`;await addEvent(item,{id:`syn_dispute_event_${crypto.randomUUID()}`,caseId:id,action:input.escalate?'case_escalated':'investigation_updated',actorId:actor.id,actorType:actor.actorType,fromStatus:from,toStatus:to,rationale:notes,correlationId:actor.correlationId,details:{owner},createdAt:now});await audit(actor,input.escalate?'synthetic_dispute_escalated':'synthetic_dispute_investigated',id,{owner,status:to});return item;},
  async addEvidence(id:string,input:{label:unknown;controlledReference:unknown;evidenceSha256:unknown},actor:DisputeActor){const item=await find(id);if(['resolved','rejected','closed'].includes(item.status))throw new SyntheticDisputeError('Closed case evidence cannot be changed.','INVALID_TRANSITION',409);const evidenceSha256=String(input.evidenceSha256??'').trim().toLowerCase();if(!/^[a-f0-9]{64}$/.test(evidenceSha256))throw new SyntheticDisputeError('Evidence SHA-256 must contain 64 lowercase hexadecimal characters.','VALIDATION_ERROR');const evidence:DisputeEvidence={id:`syn_dispute_evidence_${crypto.randomUUID()}`,caseId:id,label:text(input.label,'Evidence label',3,120),controlledReference:text(input.controlledReference,'Controlled reference',3,500),evidenceSha256,addedBy:actor.id,createdAt:new Date().toISOString()};item.evidence.push(evidence);item.lastEditedBy=actor.id;item.updatedAt=evidence.createdAt;if(db())await getQueryClient()`INSERT INTO synthetic_dispute_evidence (id,case_id,label,controlled_reference,evidence_sha256,added_by) VALUES (${evidence.id},${id},${evidence.label},${evidence.controlledReference},${evidenceSha256},${actor.id})`;await addEvent(item,{id:`syn_dispute_event_${crypto.randomUUID()}`,caseId:id,action:'evidence_added',actorId:actor.id,actorType:actor.actorType,fromStatus:item.status,toStatus:item.status,rationale:evidence.label,correlationId:actor.correlationId,details:{evidenceId:evidence.id,evidenceSha256},createdAt:evidence.createdAt});await audit(actor,'synthetic_dispute_evidence_added',evidence.id,{caseId:id,evidenceSha256});return evidence;},
  async notify(id:string,input:{channel:unknown;subject:unknown;message:unknown},actor:DisputeActor){const item=await find(id);const channel=String(input.channel);if(!['in_app','email','letter','phone'].includes(channel))throw new SyntheticDisputeError('Notification channel is invalid.','VALIDATION_ERROR');const notification:DisputeNotification={id:`syn_dispute_notification_${crypto.randomUUID()}`,caseId:id,channel:channel as DisputeNotification['channel'],subject:text(input.subject,'Subject',3,160),message:text(input.message,'Message',10,2000),deliveryStatus:'recorded',recordedBy:actor.id,createdAt:new Date().toISOString()};item.notifications.push(notification);if(db())await getQueryClient()`INSERT INTO synthetic_dispute_notifications (id,case_id,channel,subject,message,delivery_status,recorded_by) VALUES (${notification.id},${id},${notification.channel},${notification.subject},${notification.message},'recorded',${actor.id})`;await addEvent(item,{id:`syn_dispute_event_${crypto.randomUUID()}`,caseId:id,action:'customer_notification_recorded',actorId:actor.id,actorType:actor.actorType,fromStatus:item.status,toStatus:item.status,rationale:notification.subject,correlationId:actor.correlationId,details:{notificationId:notification.id,channel:notification.channel,deliveryStatus:'recorded'},createdAt:notification.createdAt});await audit(actor,'synthetic_dispute_notification_recorded',notification.id,{caseId:id,channel:notification.channel,deliveryStatus:'recorded'});return notification;},
  async submitRemediation(id:string,input:{type:unknown;reason:unknown},actor:DisputeActor){const item=await find(id);if(!['investigating','escalated'].includes(item.status))throw new SyntheticDisputeError('Investigate the case before submitting remediation.','INVALID_TRANSITION',409);const type=String(input.type) as DisputeCase['remediationType'];if(!type||!['full_refund','full_reversal','no_financial_action'].includes(type))throw new SyntheticDisputeError('Remediation type is invalid.','VALIDATION_ERROR');if(type!=='no_financial_action'&&!item.transactionId?.startsWith('syn_tx_'))throw new SyntheticDisputeError('Financial remediation requires a reconciled synthetic-ledger transaction. Record a no-financial-action decision until a controlled ledger link exists.','TRANSACTION_REQUIRED',409);const reason=text(input.reason,'Remediation reason',10,1000),now=new Date().toISOString(),from=item.status;Object.assign(item,{status:'remediation_pending',remediationType:type,remediationReason:reason,submittedBy:actor.id,submittedAt:now,lastEditedBy:actor.id,updatedAt:now});if(db())await getQueryClient()`UPDATE synthetic_dispute_cases SET status='remediation_pending',remediation_type=${type},remediation_reason=${reason},submitted_by=${actor.id},submitted_at=NOW(),last_edited_by=${actor.id},updated_at=NOW() WHERE id=${id}`;await addEvent(item,{id:`syn_dispute_event_${crypto.randomUUID()}`,caseId:id,action:'remediation_submitted',actorId:actor.id,actorType:actor.actorType,fromStatus:from,toStatus:'remediation_pending',rationale:reason,correlationId:actor.correlationId,details:{remediationType:type},createdAt:now});await audit(actor,'synthetic_dispute_remediation_submitted',id,{remediationType:type});return item;},
  async review(id:string,decision:'approved'|'rejected',note:unknown,actor:DisputeActor){const item=await find(id);if(item.status!=='remediation_pending')throw new SyntheticDisputeError('Case is not pending independent approval.','INVALID_TRANSITION',409);if(actor.actorType!=='independent_checker'||!/^external_checker_[a-f0-9]{16}$/.test(actor.id))throw new SyntheticDisputeError('Independent checker authentication is required.','INDEPENDENT_CHECKER_REQUIRED',403);if(item.submittedBy===actor.id||item.lastEditedBy===actor.id)throw new SyntheticDisputeError('Maker-checker prevents self-approval.','MAKER_CHECKER_REQUIRED',409);const rationale=text(note,'Checker rationale',10,1000),now=new Date().toISOString();let reversalId:string|undefined;if(decision==='approved'&&item.remediationType!=='no_financial_action'){const reversal=await financialSandbox.reverse(item.transactionId!,`Dispute ${item.reference}: ${item.remediationReason}`,`dispute-remediation:${item.id}`,actor);reversalId=reversal.id;}const status:DisputeStatus=decision==='approved'?'resolved':'rejected';Object.assign(item,{status,reviewedBy:actor.id,reviewedAt:now,checkerNote:rationale,remediationTransactionId:reversalId,lastEditedBy:actor.id,updatedAt:now});if(db())await getQueryClient()`UPDATE synthetic_dispute_cases SET status=${status},reviewed_by=${actor.id},reviewed_at=NOW(),checker_note=${rationale},remediation_transaction_id=${reversalId??null},last_edited_by=${actor.id},updated_at=NOW() WHERE id=${id}`;await addEvent(item,{id:`syn_dispute_event_${crypto.randomUUID()}`,caseId:id,action:decision==='approved'?'remediation_approved':'remediation_rejected',actorId:actor.id,actorType:'independent_checker',fromStatus:'remediation_pending',toStatus:status,rationale,correlationId:actor.correlationId,details:{remediationType:item.remediationType,reversalTransactionId:reversalId,balancedJournalRequired:true},createdAt:now});await audit(actor,decision==='approved'?'synthetic_dispute_remediation_approved':'synthetic_dispute_remediation_rejected',id,{reversalTransactionId:reversalId,status});return item;},
  async export(id:string,actor:DisputeActor){const item=await find(id);const evidence={schemaVersion:'1.0',classification:'SYNTHETIC DISPUTE EVIDENCE — NO REAL FUNDS',case:item,controls:{makerChecker:true,balancedRemediation:true,directBalanceEditing:false,liveTransactionUnlock:false,providerAdapters:'DISCONNECTED'},generatedAt:new Date().toISOString()};const content=JSON.stringify(evidence,null,2),evidenceSha256=crypto.createHash('sha256').update(content).digest('hex'),record={id:`syn_dispute_export_${crypto.randomUUID()}`,caseId:id,evidenceSha256,filename:`${item.reference.toLowerCase()}-evidence.json`,generatedBy:actor.id,createdAt:new Date().toISOString()};if(db())await getQueryClient()`INSERT INTO synthetic_dispute_exports (id,case_id,evidence_sha256,filename,generated_by) VALUES (${record.id},${id},${evidenceSha256},${record.filename},${actor.id})`;await audit(actor,'synthetic_dispute_exported',record.id,{caseId:id,evidenceSha256});return {record,content};}
};
