import crypto from 'node:crypto';
import { getQueryClient, isDatabaseConfigured } from '../db/db.js';
import { appendAuditEntry, appendCriticalAudit } from './auditLog.js';
import type { SandboxActor, SandboxTransaction } from './financialSandbox.js';
import type { MoneyMovementInstruction } from './moneyMovementSimulation.js';

export type ReconciliationOutcome = 'matched'|'missing_transaction'|'missing_provider_instruction'|'missing_journal'|'duplicate_reference'|'amount_mismatch'|'asset_mismatch'|'unbalanced_journal';
export type ReconciliationSeverity = 'low'|'medium'|'high'|'critical';
export type ReconciliationExceptionStatus = 'open'|'investigating'|'escalated'|'resolution_pending'|'resolved'|'accepted_risk';
export type ReconciliationActor = SandboxActor & { actorType:'admin'|'independent_checker'|'system' };
export interface ReconciliationItem { id:string; runId:string; outcome:ReconciliationOutcome; severity:ReconciliationSeverity; providerInstructionId?:string; transactionId?:string; transactionReference?:string; journalEntryReference?:string; asset?:string; amountMinor?:bigint; snapshotSha256:string; synthetic:true; createdAt:string }
export interface ReconciliationEvent { id:string; exceptionId:string; action:string; actorId:string; actorType:ReconciliationActor['actorType']; fromStatus?:ReconciliationExceptionStatus; toStatus:ReconciliationExceptionStatus; rationale:string; correlationId:string; details:Record<string,unknown>; createdAt:string }
export interface ReconciliationException { id:string; itemId:string; status:ReconciliationExceptionStatus; owner?:string; investigationNotes?:string; proposedResolution?:string; submittedBy?:string; submittedAt?:string; resolvedBy?:string; resolvedAt?:string; lastEditedBy:string; updatedAt:string; item:ReconciliationItem; events:ReconciliationEvent[]; ageingDays:number }
export interface ReconciliationRun { id:string; reference:string; businessDate:string; status:'completed'|'completed_with_breaks'; transactionCount:number; providerInstructionCount:number; journalEntryCount:number; matchedCount:number; exceptionCount:number; matchedAmountMinor:bigint; snapshotSha256:string; generatedBy:string; synthetic:true; createdAt:string; items:ReconciliationItem[] }
export interface ReconciliationOverview { runs:number; matched:number; unresolved:number; critical:number; overThreeDays:number; ledgerIntegrityBreaks:number; matchedAmountMinor:bigint; lastRunAt?:string; financialOperationsLocked:true; liveProviderAdaptersImplemented:false }

export class SyntheticReconciliationError extends Error { constructor(message:string, public readonly code:string, public readonly status=400){super(message);} }
const localRuns = new Map<string,ReconciliationRun>();
const localExceptions = new Map<string,ReconciliationException>();
const localExports = new Map<string,{id:string;runId:string;evidenceSha256:string;filename:string;generatedBy:string;createdAt:string}>();
const sha=(value:unknown)=>crypto.createHash('sha256').update(JSON.stringify(value,(_key,item)=>typeof item==='bigint'?item.toString():item)).digest('hex');
const databaseRequired=()=>process.env.NODE_ENV==='production'||isDatabaseConfigured();
const clean=(value:string,label:string,min=3,max=1000)=>{const result=value.trim().replace(/\s+/g,' ');if(result.length<min||result.length>max)throw new SyntheticReconciliationError(`${label} must be between ${min} and ${max} characters.`, 'INVALID_INPUT');return result;};
const unresolved=(status:ReconciliationExceptionStatus)=>!['resolved','accepted_risk'].includes(status);
const age=(createdAt:string)=>Math.max(0,Math.floor((Date.now()-new Date(createdAt).getTime())/86_400_000));

function assertSynthetic(transactions:SandboxTransaction[], instructions:MoneyMovementInstruction[]){
  if(transactions.some(item=>!item.synthetic||item.executionSource!=='SIMULATION'||!item.id.startsWith('syn_')))throw new SyntheticReconciliationError('Only synthetic transactions may be reconciled.','SYNTHETIC_ONLY');
  if(instructions.some(item=>!item.synthetic||item.executionSource!=='SIMULATION'||item.providerAdapterState!=='DISCONNECTED'||!item.id.startsWith('syn_rail_')))throw new SyntheticReconciliationError('Only disconnected synthetic provider instructions may be reconciled.','SYNTHETIC_ONLY');
}

type DraftItem=Omit<ReconciliationItem,'id'|'runId'|'snapshotSha256'|'createdAt'|'synthetic'>;
function detect(transactions:SandboxTransaction[], instructions:MoneyMovementInstruction[]):DraftItem[]{
  assertSynthetic(transactions,instructions);
  const items:DraftItem[]=[]; const usedInstructions=new Set<string>();
  const txRefs=new Map<string,number>(); transactions.forEach(tx=>txRefs.set(tx.reference,(txRefs.get(tx.reference)??0)+1));
  const providerRefs=new Map<string,number>(); instructions.forEach(item=>providerRefs.set(item.reference,(providerRefs.get(item.reference)??0)+1));
  const eligibleInstructions=instructions.filter(item=>['settled','returned'].includes(item.status));
  for(const tx of transactions.filter(item=>['completed','reversed'].includes(item.status))){
    const base={transactionId:tx.id,transactionReference:tx.reference,asset:tx.asset,amountMinor:tx.amountMinor};
    if((txRefs.get(tx.reference)??0)>1){items.push({...base,outcome:'duplicate_reference',severity:'critical'});continue;}
    if(tx.lines.length===0){items.push({...base,outcome:'missing_journal',severity:'critical'});continue;}
    const debit=tx.lines.reduce((sum,line)=>sum+line.debitMinor,0n); const credit=tx.lines.reduce((sum,line)=>sum+line.creditMinor,0n);
    if(tx.lines.some(line=>line.asset!==tx.asset)){items.push({...base,outcome:'asset_mismatch',severity:'critical'});continue;}
    if(debit!==credit){items.push({...base,outcome:'unbalanced_journal',severity:'critical'});continue;}
    if(debit!==tx.amountMinor||credit!==tx.amountMinor){items.push({...base,outcome:'amount_mismatch',severity:'high'});continue;}
    const exact=eligibleInstructions.find(item=>!usedInstructions.has(item.id)&&item.asset===tx.asset&&item.amountMinor===tx.amountMinor&&item.sourceReference===tx.sourceAccountId&&item.destinationReference===tx.destinationAccountId);
    const fallback=eligibleInstructions.find(item=>!usedInstructions.has(item.id)&&item.asset===tx.asset&&item.amountMinor===tx.amountMinor);
    const provider=exact??fallback;
    if(!provider){items.push({...base,outcome:'missing_provider_instruction',severity:'high'});continue;}
    usedInstructions.add(provider.id);
    if((providerRefs.get(provider.reference)??0)>1){items.push({...base,providerInstructionId:provider.id,outcome:'duplicate_reference',severity:'critical'});continue;}
    items.push({...base,providerInstructionId:provider.id,journalEntryReference:`journal:${tx.id}`,outcome:'matched',severity:'low'});
  }
  for(const provider of eligibleInstructions.filter(item=>!usedInstructions.has(item.id))){
    items.push({providerInstructionId:provider.id,asset:provider.asset,amountMinor:provider.amountMinor,outcome:(providerRefs.get(provider.reference)??0)>1?'duplicate_reference':'missing_transaction',severity:(providerRefs.get(provider.reference)??0)>1?'critical':'high'});
  }
  return items;
}

async function audit(actor:ReconciliationActor,action:string,targetId:string,details:Record<string,unknown>={}){await appendAuditEntry({adminId:actor.id,adminEmail:actor.email,action,target:'synthetic-reconciliation',targetId,ip:actor.ip,details:{...details,synthetic:true,financialOperationsLocked:true,correlationId:actor.correlationId}});}

type RunRow={id:string;reference:string;business_date:string|Date;status:ReconciliationRun['status'];transaction_count:number;provider_instruction_count:number;journal_entry_count:number;matched_count:number;exception_count:number;matched_amount_minor:string;snapshot_sha256:string;generated_by:string;created_at:string|Date};
type ItemRow={id:string;run_id:string;outcome:ReconciliationOutcome;severity:ReconciliationSeverity;provider_instruction_id:string|null;transaction_id:string|null;transaction_reference:string|null;journal_entry_reference:string|null;asset:string|null;amount_minor:string|null;snapshot_sha256:string;created_at:string|Date};
type ExceptionRow={id:string;item_id:string;status:ReconciliationExceptionStatus;owner:string|null;investigation_notes:string|null;proposed_resolution:string|null;submitted_by:string|null;submitted_at:string|Date|null;resolved_by:string|null;resolved_at:string|Date|null;last_edited_by:string;updated_at:string|Date};
type EventRow={id:string;exception_id:string;action:string;actor_id:string;actor_type:ReconciliationActor['actorType'];from_status:ReconciliationExceptionStatus|null;to_status:ReconciliationExceptionStatus;rationale:string;request_correlation_id:string;details:Record<string,unknown>;created_at:string|Date};
const mapItem=(row:ItemRow):ReconciliationItem=>({id:row.id,runId:row.run_id,outcome:row.outcome,severity:row.severity,providerInstructionId:row.provider_instruction_id??undefined,transactionId:row.transaction_id??undefined,transactionReference:row.transaction_reference??undefined,journalEntryReference:row.journal_entry_reference??undefined,asset:row.asset??undefined,amountMinor:row.amount_minor===null?undefined:BigInt(row.amount_minor),snapshotSha256:row.snapshot_sha256,synthetic:true,createdAt:new Date(row.created_at).toISOString()});

async function listDatabase(){
  const sql=getQueryClient();
  const runRows=await sql<RunRow[]>`SELECT id,reference,business_date,status,transaction_count,provider_instruction_count,journal_entry_count,matched_count,exception_count,matched_amount_minor::text,snapshot_sha256,generated_by,created_at FROM synthetic_reconciliation_runs ORDER BY created_at DESC LIMIT 90`;
  const runs:ReconciliationRun[]=[];
  for(const row of runRows){const itemRows=await sql<ItemRow[]>`SELECT id,run_id,outcome,severity,provider_instruction_id,transaction_id,transaction_reference,journal_entry_reference,asset,amount_minor::text,snapshot_sha256,created_at FROM synthetic_reconciliation_items WHERE run_id=${row.id} ORDER BY created_at,id`;runs.push({id:row.id,reference:row.reference,businessDate:new Date(row.business_date).toISOString().slice(0,10),status:row.status,transactionCount:row.transaction_count,providerInstructionCount:row.provider_instruction_count,journalEntryCount:row.journal_entry_count,matchedCount:row.matched_count,exceptionCount:row.exception_count,matchedAmountMinor:BigInt(row.matched_amount_minor),snapshotSha256:row.snapshot_sha256,generatedBy:row.generated_by,synthetic:true,createdAt:new Date(row.created_at).toISOString(),items:itemRows.map(mapItem)});}
  const exceptionRows=await sql<ExceptionRow[]>`SELECT id,item_id,status,owner,investigation_notes,proposed_resolution,submitted_by,submitted_at,resolved_by,resolved_at,last_edited_by,updated_at FROM synthetic_reconciliation_exceptions ORDER BY updated_at DESC LIMIT 1000`;
  const items=new Map(runs.flatMap(run=>run.items).map(item=>[item.id,item])); const exceptions:ReconciliationException[]=[];
  for(const row of exceptionRows){const item=items.get(row.item_id);if(!item)continue;const eventRows=await sql<EventRow[]>`SELECT id,exception_id,action,actor_id,actor_type,from_status,to_status,rationale,request_correlation_id,details,created_at FROM synthetic_reconciliation_events WHERE exception_id=${row.id} ORDER BY created_at,id`;const events=eventRows.map(e=>({id:e.id,exceptionId:e.exception_id,action:e.action,actorId:e.actor_id,actorType:e.actor_type,fromStatus:e.from_status??undefined,toStatus:e.to_status,rationale:e.rationale,correlationId:e.request_correlation_id,details:e.details??{},createdAt:new Date(e.created_at).toISOString()}));exceptions.push({id:row.id,itemId:row.item_id,status:row.status,owner:row.owner??undefined,investigationNotes:row.investigation_notes??undefined,proposedResolution:row.proposed_resolution??undefined,submittedBy:row.submitted_by??undefined,submittedAt:row.submitted_at?new Date(row.submitted_at).toISOString():undefined,resolvedBy:row.resolved_by??undefined,resolvedAt:row.resolved_at?new Date(row.resolved_at).toISOString():undefined,lastEditedBy:row.last_edited_by,updatedAt:new Date(row.updated_at).toISOString(),item,events,ageingDays:age(item.createdAt)});}
  return {runs,exceptions};
}

async function appendEvent(exception:ReconciliationException,event:ReconciliationEvent){exception.events.push(event);if(databaseRequired())await getQueryClient()`INSERT INTO synthetic_reconciliation_events (id,exception_id,action,actor_id,actor_type,from_status,to_status,rationale,request_correlation_id,details) VALUES (${event.id},${event.exceptionId},${event.action},${event.actorId},${event.actorType},${event.fromStatus??null},${event.toStatus},${event.rationale},${event.correlationId},${getQueryClient().json(JSON.parse(JSON.stringify(event.details)))})`;}
async function getException(id:string){const found=(databaseRequired()?(await listDatabase()).exceptions:[...localExceptions.values()]).find(item=>item.id===id);if(!found)throw new SyntheticReconciliationError('Reconciliation exception not found.','NOT_FOUND',404);return found;}

export const syntheticReconciliation={
  detect,
  async list(){const state=databaseRequired()?await listDatabase():{runs:[...localRuns.values()].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),exceptions:[...localExceptions.values()].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))};const breaks=state.exceptions.filter(item=>unresolved(item.status));const overview:ReconciliationOverview={runs:state.runs.length,matched:state.runs[0]?.matchedCount??0,unresolved:breaks.length,critical:breaks.filter(item=>item.item.severity==='critical').length,overThreeDays:breaks.filter(item=>item.ageingDays>=3).length,ledgerIntegrityBreaks:breaks.filter(item=>['missing_journal','unbalanced_journal','amount_mismatch','asset_mismatch'].includes(item.item.outcome)).length,matchedAmountMinor:state.runs[0]?.matchedAmountMinor??0n,lastRunAt:state.runs[0]?.createdAt,financialOperationsLocked:true,liveProviderAdaptersImplemented:false};return {...state,overview};},
  async run(transactions:SandboxTransaction[],instructions:MoneyMovementInstruction[],businessDate:string,actor:ReconciliationActor){
    if(actor.actorType!=='admin')throw new SyntheticReconciliationError('An authenticated administrator must generate reconciliation.','ADMIN_REQUIRED',403);
    if(!/^\d{4}-\d{2}-\d{2}$/.test(businessDate)||Number.isNaN(new Date(`${businessDate}T00:00:00Z`).getTime()))throw new SyntheticReconciliationError('A valid business date is required.','INVALID_DATE');
    await appendCriticalAudit({event:'synthetic_reconciliation_run_intent',adminId:actor.id,email:actor.email,ip:actor.ip,meta:{businessDate,synthetic:true,financialOperationsLocked:true,correlationId:actor.correlationId}});
    const drafts=detect(transactions,instructions);const now=new Date().toISOString();const id=`syn_recon_run_${crypto.randomUUID()}`;const material=drafts.map(d=>({...d,amountMinor:d.amountMinor?.toString()}));const snapshotSha256=sha({businessDate,transactions:transactions.map(t=>({id:t.id,reference:t.reference,status:t.status,asset:t.asset,amountMinor:t.amountMinor.toString(),lines:t.lines.map(l=>({...l,debitMinor:l.debitMinor.toString(),creditMinor:l.creditMinor.toString()}))})),instructions:instructions.map(i=>({id:i.id,reference:i.reference,status:i.status,asset:i.asset,amountMinor:i.amountMinor.toString(),source:i.sourceReference,destination:i.destinationReference})),items:material});
    const items:ReconciliationItem[]=drafts.map(d=>{const itemId=`syn_recon_item_${crypto.randomUUID()}`;return {...d,id:itemId,runId:id,snapshotSha256:sha({...d,runId:id,amountMinor:d.amountMinor?.toString()}),synthetic:true,createdAt:now};});const exceptionItems=items.filter(item=>item.outcome!=='matched');const matched=items.filter(item=>item.outcome==='matched');const run:ReconciliationRun={id,reference:`SYN-RECON-${crypto.randomBytes(6).toString('hex').toUpperCase()}`,businessDate,status:exceptionItems.length?'completed_with_breaks':'completed',transactionCount:transactions.length,providerInstructionCount:instructions.length,journalEntryCount:transactions.filter(item=>item.lines.length>0).length,matchedCount:matched.length,exceptionCount:exceptionItems.length,matchedAmountMinor:matched.reduce((sum,item)=>sum+(item.amountMinor??0n),0n),snapshotSha256,generatedBy:actor.id,synthetic:true,createdAt:now,items};
    const exceptions=exceptionItems.map(item=>{const exceptionId=`syn_recon_exception_${crypto.randomUUID()}`;const event:ReconciliationEvent={id:`syn_recon_event_${crypto.randomUUID()}`,exceptionId,action:'exception_opened',actorId:'reconciliation_engine',actorType:'system',toStatus:'open',rationale:`Detected ${item.outcome.replaceAll('_',' ')} during immutable synthetic reconciliation.`,correlationId:actor.correlationId,details:{runId:id,itemSnapshotSha256:item.snapshotSha256},createdAt:now};return {id:exceptionId,itemId:item.id,status:'open' as const,lastEditedBy:'reconciliation_engine',updatedAt:now,item,events:[event],ageingDays:0};});
    if(databaseRequired()){const sql=getQueryClient();await sql.begin(async tx=>{await tx`INSERT INTO synthetic_reconciliation_runs (id,reference,business_date,status,transaction_count,provider_instruction_count,journal_entry_count,matched_count,exception_count,matched_amount_minor,snapshot_sha256,generated_by) VALUES (${run.id},${run.reference},${businessDate},${run.status},${run.transactionCount},${run.providerInstructionCount},${run.journalEntryCount},${run.matchedCount},${run.exceptionCount},${run.matchedAmountMinor.toString()},${run.snapshotSha256},${actor.id})`;for(const item of items)await tx`INSERT INTO synthetic_reconciliation_items (id,run_id,outcome,severity,provider_instruction_id,transaction_id,transaction_reference,journal_entry_reference,asset,amount_minor,snapshot_sha256) VALUES (${item.id},${id},${item.outcome},${item.severity},${item.providerInstructionId??null},${item.transactionId??null},${item.transactionReference??null},${item.journalEntryReference??null},${item.asset??null},${item.amountMinor?.toString()??null},${item.snapshotSha256})`;for(const exception of exceptions){await tx`INSERT INTO synthetic_reconciliation_exceptions (id,item_id,status,last_edited_by) VALUES (${exception.id},${exception.itemId},'open','reconciliation_engine')`;const event=exception.events[0];await tx`INSERT INTO synthetic_reconciliation_events (id,exception_id,action,actor_id,actor_type,from_status,to_status,rationale,request_correlation_id,details) VALUES (${event.id},${exception.id},${event.action},${event.actorId},${event.actorType},NULL,'open',${event.rationale},${event.correlationId},${tx.json(JSON.parse(JSON.stringify(event.details)))})`;}});}else{localRuns.set(id,run);exceptions.forEach(item=>localExceptions.set(item.id,item));}
    await audit(actor,'synthetic_reconciliation_completed',id,{reference:run.reference,status:run.status,matchedCount:run.matchedCount,exceptionCount:run.exceptionCount,snapshotSha256});return run;
  },
  async investigate(id:string,input:{owner:string;notes:string;escalate?:boolean},actor:ReconciliationActor){const exception=await getException(id);if(!['open','investigating','escalated'].includes(exception.status))throw new SyntheticReconciliationError('This exception cannot be edited in its current state.','INVALID_TRANSITION',409);const owner=clean(input.owner,'Owner',3,120);const notes=clean(input.notes,'Investigation notes',10,1000);const from=exception.status;const to:ReconciliationExceptionStatus=input.escalate?'escalated':'investigating';exception.status=to;exception.owner=owner;exception.investigationNotes=notes;exception.lastEditedBy=actor.id;exception.updatedAt=new Date().toISOString();if(databaseRequired())await getQueryClient()`UPDATE synthetic_reconciliation_exceptions SET status=${to},owner=${owner},investigation_notes=${notes},last_edited_by=${actor.id},updated_at=NOW() WHERE id=${id}`;const event={id:`syn_recon_event_${crypto.randomUUID()}`,exceptionId:id,action:input.escalate?'exception_escalated':'investigation_updated',actorId:actor.id,actorType:actor.actorType,fromStatus:from,toStatus:to,rationale:notes,correlationId:actor.correlationId,details:{owner},createdAt:exception.updatedAt} satisfies ReconciliationEvent;await appendEvent(exception,event);await audit(actor,event.action,id,{status:to,owner});return exception;},
  async submitResolution(id:string,proposal:string,actor:ReconciliationActor){const exception=await getException(id);if(!['investigating','escalated'].includes(exception.status))throw new SyntheticReconciliationError('Investigate or escalate the exception before submitting a resolution.','INVALID_TRANSITION',409);const reason=clean(proposal,'Proposed resolution',10,1000);const from=exception.status;exception.status='resolution_pending';exception.proposedResolution=reason;exception.submittedBy=actor.id;exception.submittedAt=new Date().toISOString();exception.lastEditedBy=actor.id;exception.updatedAt=exception.submittedAt;if(databaseRequired())await getQueryClient()`UPDATE synthetic_reconciliation_exceptions SET status='resolution_pending',proposed_resolution=${reason},submitted_by=${actor.id},submitted_at=NOW(),last_edited_by=${actor.id},updated_at=NOW() WHERE id=${id}`;const event={id:`syn_recon_event_${crypto.randomUUID()}`,exceptionId:id,action:'resolution_submitted',actorId:actor.id,actorType:actor.actorType,fromStatus:from,toStatus:'resolution_pending',rationale:reason,correlationId:actor.correlationId,details:{},createdAt:exception.updatedAt} satisfies ReconciliationEvent;await appendEvent(exception,event);await audit(actor,event.action,id,{status:'resolution_pending'});return exception;},
  async resolve(id:string,decision:'resolved'|'accepted_risk',rationale:string,actor:ReconciliationActor){const exception=await getException(id);if(exception.status!=='resolution_pending')throw new SyntheticReconciliationError('Exception is not pending independent approval.','INVALID_TRANSITION',409);if(actor.actorType!=='independent_checker'||!/^external_checker_[a-f0-9]{16}$/.test(actor.id))throw new SyntheticReconciliationError('Independent checker authentication is required.','INDEPENDENT_CHECKER_REQUIRED',403);if(exception.submittedBy===actor.id||exception.lastEditedBy===actor.id)throw new SyntheticReconciliationError('Maker-checker prevents self-approval.','MAKER_CHECKER_REQUIRED',409);const reason=clean(rationale,'Checker rationale',10,1000);exception.status=decision;exception.resolvedBy=actor.id;exception.resolvedAt=new Date().toISOString();exception.updatedAt=exception.resolvedAt;if(databaseRequired())await getQueryClient()`UPDATE synthetic_reconciliation_exceptions SET status=${decision},resolved_by=${actor.id},resolved_at=NOW(),updated_at=NOW() WHERE id=${id}`;const event={id:`syn_recon_event_${crypto.randomUUID()}`,exceptionId:id,action:'exception_resolved',actorId:actor.id,actorType:'independent_checker',fromStatus:'resolution_pending',toStatus:decision,rationale:reason,correlationId:actor.correlationId,details:{decision},createdAt:exception.updatedAt} satisfies ReconciliationEvent;await appendEvent(exception,event);await audit(actor,event.action,id,{status:decision});return exception;},
  async export(runId:string,actor:ReconciliationActor){const state=await this.list();const run=state.runs.find(item=>item.id===runId);if(!run)throw new SyntheticReconciliationError('Reconciliation run not found.','NOT_FOUND',404);const exceptions=state.exceptions.filter(item=>item.item.runId===run.id);const evidence={schemaVersion:'1.0',classification:'SYNTHETIC RECONCILIATION EVIDENCE — NO REAL FUNDS',run:{...run,matchedAmountMinor:run.matchedAmountMinor.toString(),items:run.items.map(item=>({...item,amountMinor:item.amountMinor?.toString()}))},exceptions:exceptions.map(item=>({...item,item:{...item.item,amountMinor:item.item.amountMinor?.toString()}})),controls:{immutableSnapshots:true,makerChecker:true,balanceMutation:false,liveTransactionUnlock:false,providerAdapters:'DISCONNECTED'}};const content=JSON.stringify(evidence,null,2);const evidenceSha256=crypto.createHash('sha256').update(content).digest('hex');const record={id:`syn_recon_export_${crypto.randomUUID()}`,runId,evidenceSha256,filename:`${run.reference.toLowerCase()}-${run.businessDate}.json`,generatedBy:actor.id,createdAt:new Date().toISOString()};if(databaseRequired())await getQueryClient()`INSERT INTO synthetic_reconciliation_exports (id,run_id,evidence_sha256,filename,generated_by) VALUES (${record.id},${runId},${evidenceSha256},${record.filename},${actor.id})`;else localExports.set(record.id,record);await audit(actor,'synthetic_reconciliation_exported',record.id,{runId,evidenceSha256,filename:record.filename});return {record,content};},
  resetForTests(){localRuns.clear();localExceptions.clear();localExports.clear();}
};
