import { Helmet } from '@dr.pogodin/react-helmet';
import { useCallback,useEffect,useState } from 'react';
import { CheckCircle2,ClipboardCheck,Loader2,LockKeyhole,RefreshCw,Send,XCircle } from 'lucide-react';
import AdminLayout from '@/layouts/AdminLayout';
import { authHeaders } from '@/lib/adminAuth';

type Kind='penetration_test'|'disaster_recovery'|'compliance_acceptance';
type Exercise={id:string;kind:Kind;title:string;scope:string;owner:string;provider:string|null;status:string;outcome:string;evidenceUrl:string|null;evidenceSha256:string|null;criticalFindings:number;highFindings:number;openFindings:number;completedAt:string|null;expiresAt:string|null;reviewNote:string|null;createdAt:string};
const initial={kind:'penetration_test' as Kind,title:'',scope:'',owner:'',provider:'',outcome:'not_run',evidenceUrl:'',evidenceSha256:'',startedAt:'',completedAt:'',expiresAt:'',criticalFindings:0,highFindings:0,openFindings:0,notes:''};

export default function AssuranceExercisesPage(){
 const [items,setItems]=useState<Exercise[]>([]),[form,setForm]=useState(initial),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/admin/assurance-exercises',{headers:authHeaders()});const b=await r.json();if(!r.ok)throw new Error(b.error);setItems(b.exercises??[]);}catch(e){setError(e instanceof Error?e.message:'Unable to load assurance exercises.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 async function mutate(body:Record<string,unknown>){setBusy(true);setError('');try{const r=await fetch('/api/admin/assurance-exercises',{method:'POST',headers:{...authHeaders(),'Content-Type':'application/json'},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw new Error(b.error);await load();return true;}catch(e){setError(e instanceof Error?e.message:'Unable to update exercise.');return false;}finally{setBusy(false);}}
 async function create(e:React.FormEvent){e.preventDefault();if(await mutate({action:'save',...form}))setForm(initial);}
 async function review(item:Exercise,decision:'accepted'|'rejected'){const note=window.prompt(`${decision==='accepted'?'Acceptance':'Rejection'} rationale (minimum 10 characters)`);if(note)await mutate({action:'review',id:item.id,decision,note});}
 return <AdminLayout title="Assurance Exercises"><Helmet><title>Assurance Exercises | City Gate Capital Admin</title><meta name="robots" content="noindex, nofollow"/></Helmet><div className="space-y-6">
  <section className="rounded-2xl border border-cyan-400/20 bg-cyan-400/[0.06] p-6"><div className="flex items-start gap-3"><ClipboardCheck className="mt-1 text-cyan-300"/><div><h1 className="text-2xl font-bold text-white">Independent assurance register</h1><p className="mt-2 max-w-3xl text-sm text-white/50">Track penetration tests, isolated recovery exercises and compliance acceptance with controlled evidence references, remediation counts and independent review.</p></div></div><div className="mt-5 flex gap-3 rounded-xl border border-red-400/20 bg-red-400/[0.06] p-4"><LockKeyhole className="w-5 h-5 text-red-300 shrink-0"/><p className="text-xs text-red-200/65"><strong className="text-red-200">Acceptance never enables real funds.</strong> Provider, sponsor, legal and controlled-pilot gates remain separate and fail closed.</p></div></section>
  {error&&<p className="rounded-xl border border-red-400/20 bg-red-400/[0.06] p-3 text-sm text-red-200">{error}</p>}
  <form onSubmit={create} className="grid gap-3 rounded-2xl border border-white/[0.07] bg-white/[0.025] p-5 md:grid-cols-2 lg:grid-cols-4">
   <select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value as Kind})} className="rounded-lg border border-white/10 bg-black/30 p-2.5 text-sm"><option value="penetration_test">Penetration test</option><option value="disaster_recovery">Disaster recovery</option><option value="compliance_acceptance">Compliance acceptance</option></select>
   <input required minLength={3} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Exercise title" className="rounded-lg border border-white/10 bg-black/30 p-2.5 text-sm"/>
   <input required minLength={2} value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})} placeholder="Control owner" className="rounded-lg border border-white/10 bg-black/30 p-2.5 text-sm"/>
   <input value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})} placeholder="Independent assessor/provider" className="rounded-lg border border-white/10 bg-black/30 p-2.5 text-sm"/>
   <textarea required minLength={10} value={form.scope} onChange={e=>setForm({...form,scope:e.target.value})} placeholder="Approved scope, systems, exclusions and acceptance criteria" className="md:col-span-2 rounded-lg border border-white/10 bg-black/30 p-2.5 text-sm"/>
   <select value={form.outcome} onChange={e=>setForm({...form,outcome:e.target.value})} className="rounded-lg border border-white/10 bg-black/30 p-2.5 text-sm"><option value="not_run">Not run</option><option value="passed">Passed</option><option value="passed_with_findings">Passed with findings</option><option value="failed">Failed</option></select>
   <input type="date" value={form.completedAt} onChange={e=>setForm({...form,completedAt:e.target.value})} className="rounded-lg border border-white/10 bg-black/30 p-2.5 text-sm"/>
   <input type="url" value={form.evidenceUrl} onChange={e=>setForm({...form,evidenceUrl:e.target.value})} placeholder="HTTPS controlled evidence URL" className="md:col-span-2 rounded-lg border border-white/10 bg-black/30 p-2.5 text-sm"/>
   <input value={form.evidenceSha256} onChange={e=>setForm({...form,evidenceSha256:e.target.value})} placeholder="SHA-256 report digest" className="md:col-span-2 rounded-lg border border-white/10 bg-black/30 p-2.5 font-mono text-xs"/>
   {(['criticalFindings','highFindings','openFindings'] as const).map(key=><label key={key} className="text-xs text-white/40">{key.replace('Findings',' findings')}<input type="number" min="0" value={form[key]} onChange={e=>setForm({...form,[key]:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-white/10 bg-black/30 p-2.5 text-sm"/></label>)}
   <button disabled={busy} className="self-end rounded-lg bg-cyan-300 px-4 py-2.5 text-sm font-semibold text-black disabled:opacity-50">{busy?'Saving…':'Create exercise'}</button>
  </form>
  <section className="rounded-2xl border border-white/[0.07] bg-white/[0.025] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Exercise history</h2><button onClick={()=>void load()} className="flex items-center gap-1 text-sm text-white/50"><RefreshCw size={14}/>Refresh</button></div>{loading?<Loader2 className="mx-auto my-12 animate-spin text-white/30"/>:items.length===0?<p className="py-12 text-center text-sm text-white/30">No assurance exercises recorded.</p>:<div className="mt-4 space-y-3">{items.map(item=><article key={item.id} className="rounded-xl border border-white/[0.07] bg-black/20 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase text-cyan-300">{item.kind.replaceAll('_',' ')}</p><h3 className="mt-1 font-semibold">{item.title}</h3><p className="mt-1 text-xs text-white/40">{item.owner}{item.provider?` · ${item.provider}`:''}</p><p className="mt-2 text-xs text-white/45">Outcome {item.outcome.replaceAll('_',' ')} · Critical {item.criticalFindings} · High {item.highFindings} · Open {item.openFindings}</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-white/5 px-3 py-1 text-xs uppercase text-white/60">{item.status}</span>{['planned','in_progress','rejected'].includes(item.status)&&<button disabled={busy} onClick={()=>void mutate({action:'submit',id:item.id})} className="flex items-center gap-1 rounded-lg bg-primary/15 px-3 py-1.5 text-xs text-primary"><Send size={12}/>Submit</button>}{item.status==='submitted'&&<><button disabled={busy} onClick={()=>void review(item,'accepted')} className="text-emerald-300"><CheckCircle2 size={18}/></button><button disabled={busy} onClick={()=>void review(item,'rejected')} className="text-red-300"><XCircle size={18}/></button></>}</div></div>{item.reviewNote&&<p className="mt-3 border-t border-white/5 pt-3 text-xs text-white/40">Review: {item.reviewNote}</p>}</article>)}</div>}</section>
 </div></AdminLayout>;
}
