import { Helmet } from '@dr.pogodin/react-helmet';
import { Edit3, Link2, Loader2, Plus, RefreshCw, Search, ShieldCheck, Users, X } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import AdminLayout from '@/layouts/AdminLayout';
import { authHeaders } from '@/lib/adminAuth';

type Customer = { id: string; name: string; email: string; status: string };
type Relationship = { id: string; customerId: string; relatedCustomerId: string; relationshipType: string; status: string; label: string; notes: string; customer: Customer | null; relatedCustomer: Customer | null; updatedAt: string };
const TYPES = ['joint_holder','beneficial_owner','director','authorised_user','beneficiary','guarantor','household','business_contact'];
const EMPTY = { customerId: '', relatedCustomerId: '', relationshipType: 'beneficiary', status: 'pending', label: '', notes: '' };

export default function AdminCustomerRelationships() {
  const [customers, setCustomers] = useState<Customer[]>([]); const [relationships, setRelationships] = useState<Relationship[]>([]);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [query, setQuery] = useState('');
  const [form, setForm] = useState(EMPTY); const [editing, setEditing] = useState<Relationship | null>(null); const [open, setOpen] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [usersResponse, relationshipsResponse] = await Promise.all([fetch('/api/admin/users?limit=100', { headers: authHeaders(), credentials: 'same-origin' }), fetch('/api/admin/customer-relationships', { headers: authHeaders(), credentials: 'same-origin' })]); const [usersBody, relationshipsBody] = await Promise.all([usersResponse.json(), relationshipsResponse.json()]); if (!usersResponse.ok) throw new Error(usersBody.error); if (!relationshipsResponse.ok) throw new Error(relationshipsBody.error); setCustomers(usersBody.data); setRelationships(relationshipsBody.data); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load customer relationships.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => { const needle = query.toLowerCase().trim(); return relationships.filter(item => !needle || [item.customer?.name,item.customer?.email,item.relatedCustomer?.name,item.relatedCustomer?.email,item.relationshipType,item.label].some(value => value?.toLowerCase().includes(needle))); }, [query, relationships]);
  function beginCreate() { setEditing(null); setForm(EMPTY); setOpen(true); }
  function beginEdit(item: Relationship) { setEditing(item); setForm({ customerId: item.customerId, relatedCustomerId: item.relatedCustomerId, relationshipType: item.relationshipType, status: item.status, label: item.label, notes: item.notes }); setOpen(true); }
  async function save() { setBusy(true); setError(''); try { const response = await fetch('/api/admin/customer-relationships', { method: 'POST', credentials: 'same-origin', headers: { ...authHeaders(), 'Content-Type': 'application/json', 'X-Request-ID': crypto.randomUUID() }, body: JSON.stringify(editing ? { action: 'update', id: editing.id, relationshipType: form.relationshipType, status: form.status, label: form.label, notes: form.notes } : { action: 'create', ...form }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setOpen(false); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save customer relationship.'); } finally { setBusy(false); } }
  const input = 'w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-sm text-white outline-none focus:border-[#C9A84C]/50';
  return <AdminLayout title="Customer Relationships"><Helmet><title>Customer Relationships | City Gate Capital Admin</title></Helmet><div className="space-y-6">
    <section className="rounded-2xl border border-[#C9A84C]/20 bg-[#C9A84C]/[0.05] p-6"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2 text-sm font-semibold text-[#E8C96A]"><Link2 className="h-5 w-5"/>CUSTOMER RELATIONSHIP CONTROL</div><h1 className="mt-2 text-2xl font-bold text-white">Select, link and maintain customer relationships</h1><p className="mt-2 max-w-3xl text-sm text-white/45">Associate existing profiles for administration and review. A relationship record does not grant account access, signing authority, ownership or permission to move funds.</p></div><button onClick={beginCreate} className="flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#C9A84C] to-[#F0D080] px-4 py-3 text-sm font-bold text-black"><Plus className="h-4 w-4"/>Create relationship</button></div><div className="mt-5 flex gap-3 rounded-xl border border-emerald-400/20 bg-emerald-400/[0.05] p-4 text-xs text-emerald-100/65"><ShieldCheck className="h-5 w-5 shrink-0 text-emerald-300"/>Every create and edit requires a super-administrator session, CSRF protection, validated customer IDs and an immutable audit event.</div></section>
    {error&&<div className="rounded-xl border border-red-400/20 bg-red-400/[0.06] p-3 text-sm text-red-200">{error}</div>}
    <section className="rounded-2xl border border-white/[0.07] bg-white/[0.025] p-5"><div className="flex items-center justify-between gap-3"><div className="flex flex-1 items-center rounded-xl border border-white/10 bg-black/25 px-3"><Search className="h-4 w-4 text-white/30"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search customer, email, type or label" className="w-full bg-transparent px-3 py-2.5 text-sm text-white outline-none"/></div><button onClick={()=>void load()} className="rounded-xl border border-white/10 p-2.5 text-white/50"><RefreshCw className="h-4 w-4"/></button></div>{loading?<div className="flex justify-center py-16"><Loader2 className="animate-spin text-white/30"/></div>:filtered.length===0?<div className="py-16 text-center"><Users className="mx-auto h-8 w-8 text-white/15"/><p className="mt-3 text-sm text-white/30">No customer relationships found.</p></div>:<div className="mt-4 space-y-2">{filtered.map(item=><article key={item.id} className="flex flex-col gap-4 rounded-xl border border-white/[0.07] bg-black/20 p-4 md:flex-row md:items-center"><div className="flex-1"><div className="flex flex-wrap items-center gap-2 text-sm"><span className="font-semibold text-white">{item.customer?.name??'Unknown customer'}</span><span className="text-white/25">→</span><span className="font-semibold text-white">{item.relatedCustomer?.name??'Unknown customer'}</span></div><p className="mt-1 text-xs text-white/35">{item.customer?.email} · {item.relatedCustomer?.email}</p></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#C9A84C]/10 px-2.5 py-1 text-[11px] text-[#D8BC68]">{item.relationshipType.replaceAll('_',' ')}</span><span className={`rounded-full px-2.5 py-1 text-[11px] ${item.status==='active'?'bg-emerald-400/10 text-emerald-300':item.status==='inactive'?'bg-white/5 text-white/35':'bg-amber-400/10 text-amber-300'}`}>{item.status}</span>{item.label&&<span className="text-xs text-white/35">{item.label}</span>}<button onClick={()=>beginEdit(item)} className="rounded-lg border border-white/10 p-2 text-white/45 hover:text-white"><Edit3 className="h-4 w-4"/></button></div></article>)}</div>}</section>
    {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4" onClick={()=>setOpen(false)}><section onClick={e=>e.stopPropagation()} className="w-full max-w-xl rounded-2xl border border-[#C9A84C]/20 bg-[#0A0A0A] p-6"><div className="flex items-center justify-between"><h2 className="font-bold text-white">{editing?'Edit relationship':'Create relationship'}</h2><button onClick={()=>setOpen(false)} className="text-white/30"><X className="h-5 w-5"/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs text-white/40">Primary customer<select disabled={!!editing} value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value})} className={`${input} mt-1`}><option value="">Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} · {c.email}</option>)}</select></label><label className="text-xs text-white/40">Related customer<select disabled={!!editing} value={form.relatedCustomerId} onChange={e=>setForm({...form,relatedCustomerId:e.target.value})} className={`${input} mt-1`}><option value="">Select customer</option>{customers.filter(c=>c.id!==form.customerId).map(c=><option key={c.id} value={c.id}>{c.name} · {c.email}</option>)}</select></label><label className="text-xs text-white/40">Relationship type<select value={form.relationshipType} onChange={e=>setForm({...form,relationshipType:e.target.value})} className={`${input} mt-1`}>{TYPES.map(type=><option key={type} value={type}>{type.replaceAll('_',' ')}</option>)}</select></label><label className="text-xs text-white/40">Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className={`${input} mt-1`}><option value="pending">pending</option><option value="active">active</option><option value="inactive">inactive</option></select></label><label className="text-xs text-white/40 sm:col-span-2">Label<input value={form.label} onChange={e=>setForm({...form,label:e.target.value})} maxLength={80} placeholder="Optional internal label" className={`${input} mt-1`}/></label><label className="text-xs text-white/40 sm:col-span-2">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} maxLength={500} placeholder="Controlled administration notes" className={`${input} mt-1 min-h-24`}/></label></div><div className="mt-6 flex gap-3"><button onClick={()=>setOpen(false)} className="flex-1 rounded-xl border border-white/10 py-2.5 text-sm text-white/50">Cancel</button><button disabled={busy||!form.customerId||!form.relatedCustomerId} onClick={()=>void save()} className="flex-1 rounded-xl bg-gradient-to-r from-[#C9A84C] to-[#F0D080] py-2.5 text-sm font-bold text-black disabled:opacity-40">{busy?'Saving…':editing?'Save changes':'Create relationship'}</button></div></section></div>}
  </div></AdminLayout>;
}
