import AdminLayout from '@/layouts/AdminLayout';
import { authHeaders } from '@/lib/adminAuth';
import { Helmet } from '@dr.pogodin/react-helmet';
import { Building2, CheckCircle2, Loader2, LockKeyhole, Plus, RefreshCw, Send, ShieldCheck } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';

type Status = 'draft'|'submitted'|'verified'|'rejected'|'expired';
type Entity = { id:string; legalName:string; jurisdiction:string; registrationNumber:string; legalForm:string; registryUrl:string; registrySha256?:string; effectiveStatus:Status; expiresAt?:string };
type Owner = { id:string; controllerRef:string; ownershipBand:string; controlNature:string; providerCode:string; providerRef:string; evidenceSha256?:string; effectiveStatus:Status; expiresAt?:string; active:boolean };
type Snapshot = { entity:Entity|null; owners:Owner[]; assessment:{entityVerified:boolean;ownersVerified:boolean;verified:boolean;activeOwnerCount:number}; financialOperationsLocked:boolean };
const blankEntity = { legalName:'', jurisdiction:'United Kingdom', registrationNumber:'', legalForm:'', registryUrl:'', registrySha256:'', expiresAt:'' };
const blankOwner = { controllerRef:'', ownershipBand:'25-50', controlNature:'', providerCode:'', providerRef:'', evidenceSha256:'', expiresAt:'' };

export default function LegalEntityPage() {
  const [data,setData]=useState<Snapshot|null>(null); const [entity,setEntity]=useState(blankEntity); const [owner,setOwner]=useState(blankOwner);
  const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/admin/legal-entity',{headers:authHeaders()});const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b);if(b.entity)setEntity({legalName:b.entity.legalName,jurisdiction:b.entity.jurisdiction,registrationNumber:b.entity.registrationNumber,legalForm:b.entity.legalForm,registryUrl:b.entity.registryUrl,registrySha256:b.entity.registrySha256??'',expiresAt:b.entity.expiresAt?.slice(0,10)??''});}catch(e){setError(e instanceof Error?e.message:'Unable to load register.')}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  async function post(path:string,body:unknown){setBusy(true);setError('');setNotice('');try{const r=await fetch(path,{method:'POST',headers:{...authHeaders(),'Content-Type':'application/json'},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw new Error(b.error);setNotice('Saved successfully.');await load();return true}catch(e){setError(e instanceof Error?e.message:'Operation failed.');return false}finally{setBusy(false)}}
  async function review(path:string,id?:string){const decision=window.confirm('Verify this submitted record? Select Cancel to reject it.')?'verified':'rejected';const note=window.prompt(`${decision} rationale (minimum 10 characters):`)??'';if(note.length<10)return;await post(path,{action:'review',id,decision,note})}
  return <AdminLayout><Helmet><title>Legal Entity Verification | City Gate Capital Admin</title><meta name="robots" content="noindex,nofollow"/></Helmet><main className="p-6 space-y-5 max-w-7xl mx-auto">
    <header className="flex flex-wrap justify-between gap-4"><div><div className="flex items-center gap-2 text-primary"><Building2 size={20}/><span className="text-sm font-semibold">Legal authority gate</span></div><h1 className="text-2xl font-bold mt-1">Entity and beneficial ownership verification</h1><p className="text-sm text-foreground/45 mt-1">Public-registry metadata and opaque provider references only. No identity documents or residential data.</p></div><button onClick={()=>void load()} className="h-fit p-2 rounded-lg border border-white/10"><RefreshCw size={16}/></button></header>
    <section className="rounded-2xl border border-red-400/20 bg-red-400/5 p-4 flex gap-3"><LockKeyhole className="text-red-300 shrink-0"/><div><p className="font-semibold text-red-200">Verification cannot activate financial operations</p><p className="text-xs text-red-200/55 mt-1">External counsel, registry ownership evidence, sponsor acceptance and every remaining launch gate are still required.</p></div></section>
    {error&&<p className="rounded-xl bg-red-400/10 p-3 text-red-300 text-sm">{error}</p>}{notice&&<p className="rounded-xl bg-emerald-400/10 p-3 text-emerald-300 text-sm">{notice}</p>}
    {loading?<div className="py-20 flex justify-center"><Loader2 className="animate-spin"/></div>:<>
      <section className="grid sm:grid-cols-3 gap-3">{[['Entity',data?.entity?.effectiveStatus??'missing'],['Controllers',`${data?.assessment.activeOwnerCount??0} / ${data?.assessment.ownersVerified?'verified':'pending'}`],['Gate',data?.assessment.verified?'verified':'locked']].map(([l,v])=><div key={l} className="rounded-xl border border-white/10 p-4"><p className="text-xs text-foreground/40 uppercase">{l}</p><p className="font-bold mt-1">{v}</p></div>)}</section>
      <section className="rounded-2xl border border-white/10 p-5"><h2 className="font-semibold">Legal entity profile</h2><div className="grid md:grid-cols-2 gap-3 mt-4">{([['legalName','Legal name'],['jurisdiction','Jurisdiction'],['registrationNumber','Registration number'],['legalForm','Legal form'],['registryUrl','Official registry HTTPS URL'],['registrySha256','Registry evidence SHA-256'],['expiresAt','Evidence expiry']] as const).map(([k,l])=><label key={k} className="text-xs text-foreground/50">{l}<input type={k==='expiresAt'?'date':'text'} value={entity[k]} onChange={e=>setEntity(x=>({...x,[k]:e.target.value}))} className="mt-1 w-full rounded-lg bg-white/5 border border-white/10 p-2 text-sm"/></label>)}</div><div className="flex gap-2 mt-4"><button disabled={busy} onClick={()=>void post('/api/admin/legal-entity',{action:'save',...entity,registrySha256:entity.registrySha256||null,expiresAt:entity.expiresAt||null})} className="px-3 py-2 rounded-lg bg-primary/20 text-primary text-sm">Save draft</button>{data?.entity&&['draft','rejected','expired'].includes(data.entity.effectiveStatus)&&<button disabled={busy||!data.assessment.ownersVerified} onClick={()=>void post('/api/admin/legal-entity',{action:'submit'})} className="px-3 py-2 rounded-lg bg-sky-400/10 text-sky-300 text-sm flex gap-1"><Send size={14}/>Submit</button>}{data?.entity?.effectiveStatus==='submitted'&&<button disabled={busy} onClick={()=>void review('/api/admin/legal-entity')} className="px-3 py-2 rounded-lg bg-emerald-400/10 text-emerald-300 text-sm flex gap-1"><ShieldCheck size={14}/>Review</button>}</div></section>
      <section className="rounded-2xl border border-white/10 p-5"><h2 className="font-semibold">Beneficial owners and controllers</h2><p className="text-xs text-foreground/40 mt-1">Use an opaque controller reference—not a name, date of birth, address or document number.</p><div className="grid md:grid-cols-2 gap-3 mt-4">{data?.owners.map(o=><article key={o.id} className="rounded-xl bg-white/5 p-3"><div className="flex justify-between"><span className="font-mono text-sm">{o.controllerRef}</span><span className={o.effectiveStatus==='verified'?'text-emerald-300 text-xs':'text-amber-300 text-xs'}>{o.effectiveStatus}</span></div><p className="text-xs text-foreground/45 mt-2">{o.ownershipBand}% · {o.controlNature}</p><p className="text-xs text-foreground/35">{o.providerCode}:{o.providerRef}</p><div className="flex gap-2 mt-2">{['draft','rejected','expired'].includes(o.effectiveStatus)&&<button onClick={()=>void post('/api/admin/legal-entity/owners',{action:'submit',id:o.id})} className="text-xs text-sky-300">Submit</button>}{o.effectiveStatus==='submitted'&&<button onClick={()=>void review('/api/admin/legal-entity/owners',o.id)} className="text-xs text-emerald-300">Review</button>}{o.effectiveStatus==='verified'&&<CheckCircle2 size={14} className="text-emerald-300"/>}</div></article>)}</div>
        <div className="grid md:grid-cols-2 gap-3 mt-5">{([['controllerRef','Opaque controller reference'],['controlNature','Nature of control'],['providerCode','Approved provider code'],['providerRef','Opaque provider reference'],['evidenceSha256','Evidence SHA-256'],['expiresAt','Evidence expiry']] as const).map(([k,l])=><label key={k} className="text-xs text-foreground/50">{l}<input type={k==='expiresAt'?'date':'text'} value={owner[k]} onChange={e=>setOwner(x=>({...x,[k]:e.target.value}))} className="mt-1 w-full rounded-lg bg-white/5 border border-white/10 p-2 text-sm"/></label>)}<label className="text-xs text-foreground/50">Ownership band<select value={owner.ownershipBand} onChange={e=>setOwner(x=>({...x,ownershipBand:e.target.value}))} className="mt-1 w-full rounded-lg bg-zinc-950 border border-white/10 p-2 text-sm">{['none','0-25','25-50','50-75','75-100'].map(v=><option key={v}>{v}</option>)}</select></label></div><button disabled={busy||!data?.entity} onClick={async()=>{if(await post('/api/admin/legal-entity/owners',{action:'save',...owner,evidenceSha256:owner.evidenceSha256||null,expiresAt:owner.expiresAt||null}))setOwner(blankOwner)}} className="mt-4 px-3 py-2 rounded-lg bg-primary/20 text-primary text-sm flex gap-1"><Plus size={14}/>Add controller draft</button>
      </section>
    </>}
  </main></AdminLayout>
}
