import { Helmet } from '@dr.pogodin/react-helmet';
import { useCallback, useEffect, useState } from 'react';
import { Beaker, CheckCircle2, Loader2, LockKeyhole, Play, RefreshCw, XCircle } from 'lucide-react';
import AdminLayout from '@/layouts/AdminLayout';
import { authHeaders } from '@/lib/adminAuth';

interface Run { id: string; subjectType: string; subjectRef: string; status: 'running' | 'passed' | 'failed'; currencies: string[]; failureCode: string | null; results: Record<string, unknown>; createdAt: string; completedAt: string | null; }
interface PilotReadiness { label: string; rehearsalReady: boolean; gates: Array<{ key: string; passed: boolean; reason: string }>; controlGaps: Array<{ key: string; reason: string }>; realFundsEnabled: false; }

export default function ProviderSandboxPage() {
  const [runs, setRuns] = useState<Run[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [pilot, setPilot] = useState<PilotReadiness | null>(null);
  const [subjectType, setSubjectType] = useState<'individual' | 'business'>('individual');
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch('/api/admin/provider-sandbox', { headers: authHeaders() }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setRuns(body.data); setPilot(body.pilotReadiness); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load runs.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function run() { setBusy(true); setError(''); try { const key = `sandbox-${Date.now()}-${crypto.randomUUID()}`; const response = await fetch('/api/admin/provider-sandbox', { method: 'POST', headers: { ...authHeaders(), 'Content-Type': 'application/json', 'Idempotency-Key': key }, body: JSON.stringify({ subjectType, currencies: ['GBP','EUR','USD','CAD','AUD','CHF'] }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Sandbox run failed.'); } finally { setBusy(false); } }
  return <AdminLayout title="Provider Sandbox"><Helmet><title>Provider Sandbox | City Gate Capital Admin</title></Helmet><div className="space-y-6">
    <section className="rounded-2xl border border-violet-400/20 bg-violet-400/[0.06] p-6"><div className="flex flex-col lg:flex-row gap-5 lg:items-center lg:justify-between"><div><div className="flex items-center gap-2 text-violet-300 font-semibold"><Beaker className="w-5 h-5"/>Synthetic provider rehearsal</div><h1 className="text-2xl font-bold text-white mt-2">Accounts, FX, payments and reconciliation</h1><p className="text-white/45 text-sm mt-2 max-w-3xl">Runs provider-neutral contracts against synthetic identities only. Every reference is isolated under the syn_ namespace.</p></div><div className="flex gap-2"><select value={subjectType} onChange={e => setSubjectType(e.target.value as 'individual'|'business')} className="rounded-lg border border-white/10 bg-black/30 px-3 text-sm text-white"><option value="individual">Individual KYC</option><option value="business">Business KYB</option></select><button disabled={busy} onClick={() => void run()} className="rounded-lg bg-violet-400 px-4 py-2.5 text-sm font-semibold text-black flex items-center gap-2 disabled:opacity-50">{busy ? <Loader2 className="w-4 h-4 animate-spin"/> : <Play className="w-4 h-4"/>}Run rehearsal</button></div></div><div className="mt-5 flex gap-3 rounded-xl border border-red-400/20 bg-red-400/[0.06] p-4"><LockKeyhole className="w-5 h-5 text-red-300 shrink-0"/><div><p className="text-red-200 text-sm font-semibold">Real funds remain locked</p><p className="text-red-200/55 text-xs mt-1">This workspace cannot create customer balances, call a live provider, or change the production financial-operation gate.</p></div></div></section>
    {error && <p className="rounded-xl border border-red-400/20 bg-red-400/[0.06] p-3 text-sm text-red-200">{error}</p>}
    {pilot && <section className="rounded-2xl border border-white/[0.07] bg-white/[0.025] p-5"><div className="flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${pilot.rehearsalReady ? 'bg-emerald-400' : 'bg-amber-400'}`}/><h2 className="font-semibold text-white">{pilot.label}</h2></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-2 mt-4">{pilot.gates.map(gate => <div key={gate.key} className="rounded-lg bg-black/20 p-3 flex gap-2">{gate.passed ? <CheckCircle2 className="w-4 h-4 text-emerald-300 shrink-0"/> : <XCircle className="w-4 h-4 text-amber-300 shrink-0"/>}<div><p className="text-white/70 text-xs font-medium">{gate.key.replaceAll('_',' ')}</p><p className="text-white/30 text-[11px] mt-1">{gate.reason}</p></div></div>)}</div></section>}
    <section className="rounded-2xl border border-white/[0.07] bg-white/[0.025] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold text-white">Rehearsal history</h2><button onClick={() => void load()} className="text-white/50 flex items-center gap-1 text-sm"><RefreshCw className="w-4 h-4"/>Refresh</button></div>{loading ? <div className="py-12 flex justify-center"><Loader2 className="animate-spin text-white/30"/></div> : runs.length === 0 ? <p className="py-12 text-center text-white/30 text-sm">No sandbox runs yet.</p> : <div className="mt-4 space-y-2">{runs.map(item => <article key={item.id} className="rounded-xl border border-white/[0.07] bg-black/20 p-4 flex flex-col sm:flex-row gap-3 sm:items-center sm:justify-between"><div><div className="flex items-center gap-2">{item.status === 'passed' ? <CheckCircle2 className="w-4 h-4 text-emerald-300"/> : item.status === 'failed' ? <XCircle className="w-4 h-4 text-red-300"/> : <Loader2 className="w-4 h-4 animate-spin text-amber-300"/>}<span className="text-white text-sm font-medium">{item.subjectType === 'business' ? 'Business KYB' : 'Individual KYC'} · {item.status}</span></div><p className="text-white/30 text-xs mt-1 font-mono">{item.subjectRef}</p></div><div className="text-right"><p className="text-white/45 text-xs">{item.currencies.join(' · ')}</p><p className="text-white/25 text-xs mt-1">{new Date(item.createdAt).toLocaleString()}</p></div></article>)}</div>}</section>
  </div></AdminLayout>;
}
